// TOEIC600点対策 文法問題データ
const GRAMMAR_DATA = [
  // 品詞問題
  {id:1,q:"The manager gave a ___ presentation to the new clients.",choices:["impress","impressive","impressively","impression"],ans:1,exp:"名詞 presentation を修飾するので形容詞 impressive が正解。",cat:"品詞"},
  {id:2,q:"All employees must complete the training ___.",choices:["immediate","immediately","immediacy","immediateness"],ans:1,exp:"動詞 complete を修飾するので副詞 immediately が正解。",cat:"品詞"},
  {id:3,q:"The ___ of the new product was a great success.",choices:["launch","launching","launched","launches"],ans:0,exp:"The の後で動詞の目的語にあたる主語の位置なので名詞 launch が正解。",cat:"品詞"},
  {id:4,q:"She is responsible for the ___ of customer complaints.",choices:["handle","handled","handling","handler"],ans:2,exp:"前置詞 for の後は名詞または動名詞。handling（動名詞）が正解。",cat:"品詞"},
  {id:5,q:"This software is ___ compatible with most operating systems.",choices:["fully","full","fullness","fill"],ans:0,exp:"形容詞 compatible を修飾するので副詞 fully が正解。",cat:"品詞"},
  {id:6,q:"The committee made a ___ decision after long discussion.",choices:["careful","carefully","care","cares"],ans:0,exp:"名詞 decision を修飾するので形容詞 careful が正解。",cat:"品詞"},
  {id:7,q:"Please ensure the report is ___ before submission.",choices:["accurate","accuracy","accurately","accurateness"],ans:0,exp:"be動詞の後の補語として形容詞 accurate が正解。",cat:"品詞"},
  {id:8,q:"His ___ to the team has been invaluable.",choices:["contribute","contribution","contributing","contributed"],ans:1,exp:"所有格 His の後は名詞が来るので contribution が正解。",cat:"品詞"},
  {id:9,q:"The new policy will be implemented ___.",choices:["gradual","gradually","gradualness","graduate"],ans:1,exp:"動詞 implemented を修飾するので副詞 gradually が正解。",cat:"品詞"},
  {id:10,q:"We need a more ___ approach to solve this issue.",choices:["effective","effectively","effectiveness","effect"],ans:0,exp:"名詞 approach を修飾するので形容詞 effective が正解。",cat:"品詞"},
  // 時制
  {id:11,q:"By the time the manager arrives, the meeting ___ already.",choices:["starts","will start","will have started","started"],ans:2,exp:"未来のある時点までに完了している動作は未来完了形（will have + 過去分詞）。",cat:"時制"},
  {id:12,q:"The company ___ its profits significantly over the past five years.",choices:["increases","increased","has increased","will increase"],ans:2,exp:"over the past five years（過去から現在まで）は現在完了形が適切。",cat:"時制"},
  {id:13,q:"She ___ for this company since 2015.",choices:["works","worked","has worked","will work"],ans:2,exp:"since 2015 は継続を表すので現在完了形が正解。",cat:"時制"},
  {id:14,q:"When the CEO ___ the announcement, everyone applauded.",choices:["makes","made","will make","is making"],ans:1,exp:"過去の出来事の連続なので過去形 made が正解。",cat:"時制"},
  {id:15,q:"The new branch ___ next month.",choices:["opens","opened","will open","has opened"],ans:2,exp:"next month という未来を示す語があるので未来形 will open が正解。",cat:"時制"},
  {id:16,q:"By next year, the project ___ completed.",choices:["is","was","will be","will have been"],ans:3,exp:"未来のある時点までに完了する受動態は未来完了受動態 will have been。",cat:"時制"},
  {id:17,q:"While she ___ the report, the phone rang.",choices:["writes","was writing","wrote","will write"],ans:1,exp:"過去進行中の動作 + 過去の一瞬の動作なので過去進行形 was writing。",cat:"時制"},
  {id:18,q:"The shipment ___ yesterday but it hasn't arrived yet.",choices:["sends","is sent","was sent","will send"],ans:2,exp:"yesterday は過去を示す語なので過去形 was sent（受動態）が正解。",cat:"時制"},
  {id:19,q:"I ___ this report by the end of the day.",choices:["finish","finished","will have finished","am finishing"],ans:2,exp:"by the end of the day は未来完了形と結びつく典型表現。",cat:"時制"},
  {id:20,q:"They ___ the new system for three months now.",choices:["use","used","have been using","will use"],ans:2,exp:"for three months now は継続を表すので現在完了進行形が適切。",cat:"時制"},
  // 前置詞
  {id:21,q:"The conference will be held ___ March 15.",choices:["in","on","at","by"],ans:1,exp:"特定の日付には on を使う。",cat:"前置詞"},
  {id:22,q:"The report should be submitted ___ Friday.",choices:["until","by","since","during"],ans:1,exp:"「〜までに」という期限を表す by が正解。",cat:"前置詞"},
  {id:23,q:"The meeting room is located ___ the third floor.",choices:["in","on","at","to"],ans:1,exp:"階を表す場合は on を使う（on the third floor）。",cat:"前置詞"},
  {id:24,q:"She has worked here ___ five years.",choices:["since","for","from","during"],ans:1,exp:"期間を表す場合は for（for five years）。",cat:"前置詞"},
  {id:25,q:"The package was delivered ___ the customer's request.",choices:["according to","along with","in spite of","instead of"],ans:0,exp:"「〜に従って」は according to。",cat:"前置詞"},
  {id:26,q:"All visitors must check in ___ the reception desk.",choices:["at","in","on","to"],ans:0,exp:"特定の地点（受付）には at を使う。",cat:"前置詞"},
  {id:27,q:"The factory operates ___ a strict safety protocol.",choices:["under","over","above","beyond"],ans:0,exp:"「〜のもとで」は under。under a strict protocol。",cat:"前置詞"},
  {id:28,q:"The negotiations continued ___ midnight.",choices:["until","by","at","on"],ans:0,exp:"「〜まで（継続）」は until。",cat:"前置詞"},
  {id:29,q:"The new policy applies ___ all departments.",choices:["to","for","with","of"],ans:0,exp:"apply to ~ で「〜に適用される」。",cat:"前置詞"},
  {id:30,q:"He was praised ___ his excellent performance.",choices:["for","to","with","by"],ans:0,exp:"praise A for B「BのことでAを称賛する」。",cat:"前置詞"},
  // 関係詞
  {id:31,q:"The employee ___ proposal was accepted received an award.",choices:["who","whose","which","whom"],ans:1,exp:"後ろに名詞（proposal）が続く所有格の関係代名詞 whose が正解。",cat:"関係詞"},
  {id:32,q:"This is the product ___ we have been developing.",choices:["who","whose","which","where"],ans:2,exp:"物（product）を先行詞とする関係代名詞は which。",cat:"関係詞"},
  {id:33,q:"The manager ___ approved the budget is on vacation.",choices:["which","who","whom","whose"],ans:1,exp:"人（manager）を先行詞とし主語の働きをする関係代名詞は who。",cat:"関係詞"},
  {id:34,q:"This is the office ___ I work.",choices:["which","where","who","whose"],ans:1,exp:"場所を表す先行詞には関係副詞 where。",cat:"関係詞"},
  {id:35,q:"The reason ___ she resigned remains unclear.",choices:["why","which","who","where"],ans:0,exp:"理由を表す先行詞 reason には関係副詞 why。",cat:"関係詞"},
  // 接続詞
  {id:36,q:"___ the rain, the event was held outdoors.",choices:["Despite","Although","Because","Even"],ans:0,exp:"後ろに名詞句が続くので前置詞 despite が正解。",cat:"接続詞"},
  {id:37,q:"___ it was raining, the event was held outdoors.",choices:["Despite","In spite of","Although","Because of"],ans:2,exp:"後ろにSV（節）が続くので接続詞 although が正解。",cat:"接続詞"},
  {id:38,q:"The store will remain open ___ the holiday.",choices:["during","while","when","as"],ans:0,exp:"後ろに名詞句が続くので前置詞 during が正解。",cat:"接続詞"},
  {id:39,q:"You should call the office ___ you have any questions.",choices:["if","despite","because of","during"],ans:0,exp:"条件を表す接続詞 if が正解。",cat:"接続詞"},
  {id:40,q:"___ the budget is limited, the team did excellent work.",choices:["Because","Even though","Due to","Despite"],ans:1,exp:"後ろに節が続き、逆接の意味になるのは even though。",cat:"接続詞"},
  // 比較
  {id:41,q:"This model is ___ than the previous one.",choices:["efficient","more efficient","most efficient","efficiently"],ans:1,exp:"than があるので比較級 more efficient が正解。",cat:"比較"},
  {id:42,q:"This is the ___ option among all the choices.",choices:["good","better","best","well"],ans:2,exp:"the と among all があるので最上級 best が正解。",cat:"比較"},
  {id:43,q:"The new model runs ___ as quietly as the old one.",choices:["so","as","more","most"],ans:1,exp:"as ~ as の同等比較構文。",cat:"比較"},
  {id:44,q:"Sales this quarter were ___ higher than expected.",choices:["very","much","so","too"],ans:1,exp:"比較級を強調する語は much。",cat:"比較"},
  {id:45,q:"The more you practice, the ___ you become.",choices:["good","well","better","best"],ans:2,exp:"the more ~ the 比較級 の構文。",cat:"比較"},
  // 仮定法・態
  {id:46,q:"If the budget ___ approved, we would start the project immediately.",choices:["is","was","were","be"],ans:2,exp:"仮定法過去では be動詞は were を使う（If S were ~）。",cat:"仮定法"},
  {id:47,q:"The report ___ by the accounting team every month.",choices:["prepares","is prepared","prepared","preparing"],ans:1,exp:"主語 report は「準備される」側なので受動態 is prepared。",cat:"態"},
  {id:48,q:"The new factory ___ next year.",choices:["will build","will be built","builds","is building"],ans:1,exp:"factory は「建てられる」側なので受動態 will be built。",cat:"態"},
  {id:49,q:"If I ___ you, I would accept the offer.",choices:["am","was","were","be"],ans:2,exp:"仮定法過去の定型表現 If I were you。",cat:"仮定法"},
  {id:50,q:"The documents ___ carefully before signing.",choices:["should review","should be reviewed","reviews","reviewing"],ans:1,exp:"documents は「見直される」側なので受動態 should be reviewed。",cat:"態"},
  // 品詞（追加）
  {id:51,q:"The ___ of the new policy will take place next week.",choices:["implement","implementation","implementing","implemented"],ans:1,exp:"The の後の主語位置は名詞。implementation が正解。",cat:"品詞"},
  {id:52,q:"Her explanation was very ___.",choices:["clear","clearly","clarity","clarify"],ans:0,exp:"be動詞の補語として形容詞 clear が正解。",cat:"品詞"},
  {id:53,q:"The company values ___ among its employees.",choices:["cooperative","cooperation","cooperate","cooperatively"],ans:1,exp:"動詞 values の目的語となる名詞 cooperation が正解。",cat:"品詞"},
  {id:54,q:"He answered the question ___.",choices:["confident","confidently","confidence","confident"],ans:1,exp:"動詞 answered を修飾する副詞 confidently が正解。",cat:"品詞"},
  {id:55,q:"There has been a ___ increase in online sales.",choices:["notice","noticeable","noticeably","notices"],ans:1,exp:"名詞 increase を修飾する形容詞 noticeable が正解。",cat:"品詞"},
  {id:56,q:"The ___ between the two companies benefited both sides.",choices:["cooperate","cooperation","cooperative","cooperatively"],ans:1,exp:"The の後の主語位置なので名詞 cooperation が正解。",cat:"品詞"},
  {id:57,q:"We are looking for a highly ___ candidate.",choices:["motivate","motivation","motivated","motivating"],ans:2,exp:"名詞 candidate を修飾する形容詞的過去分詞 motivated が正解。",cat:"品詞"},
  {id:58,q:"The seminar provided ___ information about tax law.",choices:["use","useful","usefully","usefulness"],ans:1,exp:"名詞 information を修飾する形容詞 useful が正解。",cat:"品詞"},
  {id:59,q:"Please handle the equipment with ___.",choices:["care","careful","carefully","caring"],ans:0,exp:"前置詞 with の後は名詞。care が正解。",cat:"品詞"},
  {id:60,q:"The new employee adapted to the job ___.",choices:["quick","quickly","quickness","quicker"],ans:1,exp:"動詞 adapted を修飾する副詞 quickly が正解。",cat:"品詞"},
  // 時制（追加）
  {id:61,q:"She ___ the department for over a decade before retiring.",choices:["leads","led","had led","will lead"],ans:2,exp:"退職という過去の基準時よりさらに前の継続を表すので過去完了 had led。",cat:"時制"},
  {id:62,q:"The technicians ___ the machine when the alarm went off.",choices:["repair","repaired","were repairing","will repair"],ans:2,exp:"過去のある時点で進行中だった動作なので過去進行形 were repairing。",cat:"時制"},
  {id:63,q:"By the time you arrive, I ___ the presentation.",choices:["finish","will finish","will have finished","finished"],ans:2,exp:"未来のある時点までの動作の完了は未来完了形。",cat:"時制"},
  {id:64,q:"The firm ___ several new offices since its founding.",choices:["opens","opened","has opened","will open"],ans:2,exp:"since its founding（設立以来）は現在完了形と結びつく。",cat:"時制"},
  {id:65,q:"He ___ to Tokyo twice this year already.",choices:["travels","traveled","has traveled","will travel"],ans:2,exp:"this year（今年、継続中の期間）＋already は現在完了形。",cat:"時制"},
  {id:66,q:"At this time tomorrow, the team ___ the client.",choices:["meets","will be meeting","met","has met"],ans:1,exp:"未来のある時点で進行中の動作は未来進行形 will be meeting。",cat:"時制"},
  {id:67,q:"The report ___ by the time the meeting begins.",choices:["will complete","will be completed","completes","completed"],ans:1,exp:"未来のある時点までに完了する受動態は未来完了受動態が本来だが、選択肢の中では受動態 will be completed が最も適切。",cat:"時制"},
  {id:68,q:"She usually ___ the office at six, but yesterday she left at eight.",choices:["leaves","left","was leaving","has left"],ans:0,exp:"usually（習慣）は現在形 leaves が正解。",cat:"時制"},
  {id:69,q:"The company ___ its headquarters twice in the past twenty years.",choices:["moves","moved","has moved","will move"],ans:2,exp:"in the past twenty years（過去から現在までの期間）は現在完了形。",cat:"時制"},
  {id:70,q:"I will call you as soon as I ___ the airport.",choices:["reach","will reach","reached","have reached"],ans:0,exp:"時を表す副詞節（as soon as）の中では未来のことも現在形で表す。",cat:"時制"},
  // 前置詞（追加）
  {id:71,q:"The workshop is designed ___ new managers.",choices:["for","to","with","at"],ans:0,exp:"「〜向けに」は for。designed for ~。",cat:"前置詞"},
  {id:72,q:"The budget was divided ___ four departments.",choices:["among","between","with","into"],ans:3,exp:"「〜に分割する」は divide into。",cat:"前置詞"},
  {id:73,q:"He is well known ___ his attention to detail.",choices:["for","to","with","at"],ans:0,exp:"be known for ~「〜で知られている」。",cat:"前置詞"},
  {id:74,q:"The building is situated ___ the river.",choices:["along","in","on","at"],ans:0,exp:"「川沿いに」は along the river。",cat:"前置詞"},
  {id:75,q:"The negotiation resulted ___ a new partnership.",choices:["in","from","with","to"],ans:0,exp:"result in ~「〜という結果になる」。",cat:"前置詞"},
  {id:76,q:"The proposal was rejected ___ lack of funding.",choices:["due to","despite","in case of","instead of"],ans:0,exp:"「〜のために」という理由を表す due to が正解。",cat:"前置詞"},
  {id:77,q:"Please arrive ten minutes ___ the scheduled time.",choices:["before","after","by","until"],ans:0,exp:"「〜より前に」は before。",cat:"前置詞"},
  {id:78,q:"The new regulation goes ___ effect next month.",choices:["into","in","on","at"],ans:0,exp:"go into effect「施行される」という定型表現。",cat:"前置詞"},
  {id:79,q:"The candidates were evaluated ___ their experience.",choices:["based on","according","depend on","regarding to"],ans:0,exp:"based on ~「〜に基づいて」。",cat:"前置詞"},
  {id:80,q:"The store is open ___ 9 A.M. to 8 P.M.",choices:["from","since","by","at"],ans:0,exp:"from A to B「AからBまで」の定型表現。",cat:"前置詞"},
  // 関係詞（追加）
  {id:81,q:"The company for ___ she works is expanding rapidly.",choices:["who","which","whom","whose"],ans:2,exp:"前置詞 for の後の目的格は whom。",cat:"関係詞"},
  {id:82,q:"This is the year ___ the company was founded.",choices:["when","which","who","whose"],ans:0,exp:"時を表す先行詞 year には関係副詞 when。",cat:"関係詞"},
  {id:83,q:"Employees ___ performance exceeds expectations will be rewarded.",choices:["who","whom","whose","which"],ans:2,exp:"後ろに名詞 performance が続くので所有格 whose。",cat:"関係詞"},
  {id:84,q:"The new software, ___ was released last month, has many bugs.",choices:["that","which","who","whose"],ans:1,exp:"非制限用法（コンマ+関係詞）では that は使えず which を使う。",cat:"関係詞"},
  {id:85,q:"This is the client ___ we met at the conference.",choices:["whose","which","whom","where"],ans:2,exp:"人を先行詞とし目的格の働きをする関係代名詞 whom（口語では who も可）。",cat:"関係詞"},
  // 接続詞（追加）
  {id:86,q:"___ he was tired, he finished the report.",choices:["Despite","Even though","Because of","In spite of"],ans:1,exp:"後ろに節（SV）が続くので接続詞 even though。",cat:"接続詞"},
  {id:87,q:"You may leave early ___ you finish your tasks.",choices:["provided that","because of","despite","during"],ans:0,exp:"「〜という条件で」は provided that。",cat:"接続詞"},
  {id:88,q:"___ the weather, the outdoor event will proceed as planned.",choices:["Regardless of","Even though","Although","While"],ans:0,exp:"後ろに名詞句が続くので前置詞的表現 regardless of。",cat:"接続詞"},
  {id:89,q:"She continued working ___ she felt unwell.",choices:["even though","because of","due to","despite"],ans:0,exp:"後ろに節が続き逆接の意味なので even though。",cat:"接続詞"},
  {id:90,q:"The meeting was rescheduled ___ several members were unavailable.",choices:["because","because of","despite","although"],ans:0,exp:"後ろに節（SV）が続くので接続詞 because。",cat:"接続詞"},
  // 比較（追加）
  {id:91,q:"This year's turnout was ___ than last year's.",choices:["large","larger","largest","more large"],ans:1,exp:"than があるので比較級 larger が正解。",cat:"比較"},
  {id:92,q:"Of all the proposals, this one is ___ practical.",choices:["more","most","the most","much"],ans:2,exp:"three以上の中での最上級には the most が必要。",cat:"比較"},
  {id:93,q:"The new model is not ___ expensive as the old one.",choices:["so","as","than","more"],ans:0,exp:"not so ~ as の同等比較の否定形。",cat:"比較"},
  {id:94,q:"The company grew ___ faster than expected.",choices:["far","farther","farthest","far away"],ans:0,exp:"比較級を強調する far「はるかに」。",cat:"比較"},
  {id:95,q:"This is by far the ___ solution available.",choices:["good","better","best","well"],ans:2,exp:"by far the + 最上級「断然最も〜」という定型表現。",cat:"比較"},
  // 仮定法・態（追加）
  {id:96,q:"If the shipment ___ delayed, we would have informed you.",choices:["was","were","had been","is"],ans:2,exp:"過去の事実に反する仮定（仮定法過去完了）は had been。",cat:"仮定法"},
  {id:97,q:"The invoice ___ by the accounting team last week.",choices:["issues","was issued","issued","is issuing"],ans:1,exp:"invoice は「発行される」側で、last week という過去の語があるので過去形の受動態。",cat:"態"},
  {id:98,q:"If I had known about the delay, I ___ earlier.",choices:["would leave","would have left","left","leave"],ans:1,exp:"仮定法過去完了の帰結節は would have + 過去分詞。",cat:"仮定法"},
  {id:99,q:"New employees ___ orientation training during their first week.",choices:["give","are given","gives","giving"],ans:1,exp:"employees は「与えられる」側なので受動態 are given。",cat:"態"},
  {id:100,q:"The proposal ___ by the board next Monday.",choices:["will discuss","will be discussed","discusses","discussed"],ans:1,exp:"proposal は「議論される」側なので未来受動態 will be discussed。",cat:"態"},
  // 新カテゴリ: 不定詞・動名詞
  {id:101,q:"The manager decided ___ the meeting until Friday.",choices:["postponing","to postpone","postpone","postponed"],ans:1,exp:"decide は不定詞を目的語に取る動詞。decide to do。",cat:"不定詞・動名詞"},
  {id:102,q:"She enjoys ___ with international clients.",choices:["work","to work","working","worked"],ans:2,exp:"enjoy は動名詞を目的語に取る動詞。enjoy doing。",cat:"不定詞・動名詞"},
  {id:103,q:"We look forward ___ from you soon.",choices:["hear","to hear","hearing","to hearing"],ans:3,exp:"look forward to の to は前置詞なので後ろは動名詞。to hearing。",cat:"不定詞・動名詞"},
  {id:104,q:"The committee agreed ___ the new proposal.",choices:["review","to review","reviewing","reviewed"],ans:1,exp:"agree は不定詞を目的語に取る動詞。agree to do。",cat:"不定詞・動名詞"},
  {id:105,q:"It is important ___ the instructions carefully.",choices:["follow","following","to follow","followed"],ans:2,exp:"It is + 形容詞 + to do の形式主語構文。",cat:"不定詞・動名詞"},
  {id:106,q:"He avoided ___ any comments during the interview.",choices:["to make","making","make","made"],ans:1,exp:"avoid は動名詞を目的語に取る動詞。avoid doing。",cat:"不定詞・動名詞"},
  {id:107,q:"The staff was asked ___ the new procedure.",choices:["follow","following","to follow","followed"],ans:2,exp:"ask A to do の受動態: A is asked to do。",cat:"不定詞・動名詞"},
  {id:108,q:"___ a good presentation requires careful preparation.",choices:["Give","To give","Given","Gives"],ans:1,exp:"文頭の主語として不定詞（名詞的用法）を使うことができる。",cat:"不定詞・動名詞"},
  {id:109,q:"The company plans ___ its operations overseas.",choices:["expanding","to expand","expand","expanded"],ans:1,exp:"plan は不定詞を目的語に取る動詞。plan to do。",cat:"不定詞・動名詞"},
  {id:110,q:"Thank you for ___ me to the event.",choices:["invite","to invite","inviting","invited"],ans:2,exp:"前置詞 for の後は動名詞。for doing。",cat:"不定詞・動名詞"},
  // 新カテゴリ: 数量詞
  {id:111,q:"___ of the employees attended the seminar.",choices:["Most","Almost","Much","Every"],ans:0,exp:"of the + 名詞 の前で使える数量詞は most。",cat:"数量詞"},
  {id:112,q:"There were ___ complaints about the new system.",choices:["few","little","much","a little"],ans:0,exp:"可算名詞 complaints には few を使う。",cat:"数量詞"},
  {id:113,q:"We have ___ time left before the deadline.",choices:["few","many","little","several"],ans:2,exp:"不可算名詞 time には little を使う。",cat:"数量詞"},
  {id:114,q:"___ employee must complete the safety training.",choices:["All","Every","Most","Several"],ans:1,exp:"単数形の名詞を伴う数量詞は every。",cat:"数量詞"},
  {id:115,q:"Only a ___ candidates passed the final round.",choices:["few","little","much","less"],ans:0,exp:"可算名詞 candidates を伴うので a few。",cat:"数量詞"},
  // 新カテゴリ: 語彙選択・語法
  {id:116,q:"Please ___ the attached file for further details.",choices:["refer","see","attend","regard"],ans:1,exp:"see the attached file「添付ファイルをご覧ください」という定型表現。",cat:"語彙選択"},
  {id:117,q:"The new policy will ___ effect on July 1.",choices:["take","make","do","have"],ans:0,exp:"take effect「発効する」という定型表現。",cat:"語彙選択"},
  {id:118,q:"We need to ___ a decision by Friday.",choices:["take","make","do","have"],ans:1,exp:"make a decision「決定を下す」という定型表現。",cat:"語彙選択"},
  {id:119,q:"The manager will ___ care of the client's complaint.",choices:["make","take","do","have"],ans:1,exp:"take care of ~「〜の世話をする、対応する」という定型表現。",cat:"語彙選択"},
  {id:120,q:"Please ___ sure that all forms are signed.",choices:["do","make","take","have"],ans:1,exp:"make sure that ~「〜であることを確認する」という定型表現。",cat:"語彙選択"},
];
