// TOEIC600点対策 文法問題データ
const GRAMMAR_DATA = [
  // 品詞問題
  {id:1,q:"The manager gave a ___ presentation to the new clients.",choices:["impress","impressive","impressively","impression"],ans:1,exp:"名詞 presentation を修飾するので形容詞 impressive が正解。",cat:"品詞"},
  {id:2,q:"All employees must complete the training ___.",choices:["immediate","immediately","immediacy","immediateness"],ans:1,exp:"動詞 complete を修飾するので副詞 immediately が正解。",cat:"品詞"},
  {id:3,q:"The ___ of the new product was a great success.",choices:["launch","launching","launched","launches"],ans:0,exp:"The の後で動詞の目的語にあたる主語の位置なので名詞 launch が正解。",cat:"品詞"},
  {id:4,q:"She is responsible for the ___ of customer complaints.",choices:["handle","handled","handling","handler"],ans:2,exp:"前置詞 for の後は名詞または動名詞。handling（動名詞）が正解。",cat:"品詞"},
  {id:5,q:"This software is ___ compatible with most operating systems.",choices:["fully","full","fullness","fill"],ans:0,exp:"形容詞 compatible を修飾するので副詞 fully が正解。",cat:"品詞"},
  {id:6,q:"The committee made a ___ decision after long discussion.",choices:["careful","carefully","care","cares"],ans:0,exp:"名詞 decision を修飾するので形容詞 careful が正解。",cat:"品詞"},
  {id:7,q:"Please ensure the report is ___ before submission.",choices:["accurate","accuracy","accurately","accurateness"],ans:0,exp:"be動詞の後の補語として形容詞 accurate が正解。",cat:"品詞"},
  {id:8,q:"His ___ to the team has been invaluable.",choices:["contribute","contribution","contributing","contributed"],ans:1,exp:"所有格 His の後は名詞が来るので contribution が正解。",cat:"品詞"},
  {id:9,q:"The new policy will be implemented ___.",choices:["gradual","gradually","gradualness","graduate"],ans:1,exp:"動詞 implemented を修飾するので副詞 gradually が正解。",cat:"品詞"},
  {id:10,q:"We need a more ___ approach to solve this issue.",choices:["effective","effectively","effectiveness","effect"],ans:0,exp:"名詞 approach を修飾するので形容詞 effective が正解。",cat:"品詞"},
  // 時制
  {id:11,q:"By the time the manager arrives, the meeting ___ already.",choices:["starts","will start","will have started","started"],ans:2,exp:"未来のある時点までに完了している動作は未来完了形（will have + 過去分詞）。",cat:"時制"},
  {id:12,q:"The company ___ its profits significantly over the past five years.",choices:["increases","increased","has increased","will increase"],ans:2,exp:"over the past five years（過去から現在まで）は現在完了形が適切。",cat:"時制"},
  {id:13,q:"She ___ for this company since 2015.",choices:["works","worked","has worked","will work"],ans:2,exp:"since 2015 は継続を表すので現在完了形が正解。",cat:"時制"},
  {id:14,q:"When the CEO ___ the announcement, everyone applauded.",choices:["makes","made","will make","is making"],ans:1,exp:"過去の出来事の連続なので過去形 made が正解。",cat:"時制"},
  {id:15,q:"The new branch ___ next month.",choices:["opens","opened","will open","has opened"],ans:2,exp:"next month という未来を示す語があるので未来形 will open が正解。",cat:"時制"},
  {id:16,q:"By next year, the project ___ completed.",choices:["is","was","will be","will have been"],ans:3,exp:"未来のある時点までに完了する受動態は未来完了受動態 will have been。",cat:"時制"},
  {id:17,q:"While she ___ the report, the phone rang.",choices:["writes","was writing","wrote","will write"],ans:1,exp:"過去進行中の動作 + 過去の一瞬の動作なので過去進行形 was writing。",cat:"時制"},
  {id:18,q:"The shipment ___ yesterday but it hasn't arrived yet.",choices:["sends","is sent","was sent","will send"],ans:2,exp:"yesterday は過去を示す語なので過去形 was sent（受動態）が正解。",cat:"時制"},
  {id:19,q:"I ___ this report by the end of the day.",choices:["finish","finished","will have finished","am finishing"],ans:2,exp:"by the end of the day は未来完了形と結びつく典型表現。",cat:"時制"},
  {id:20,q:"They ___ the new system for three months now.",choices:["use","used","have been using","will use"],ans:2,exp:"for three months now は継続を表すので現在完了進行形が適切。",cat:"時制"},
  // 前置詞
  {id:21,q:"The conference will be held ___ March 15.",choices:["in","on","at","by"],ans:1,exp:"特定の日付には on を使う。",cat:"前置詞"},
  {id:22,q:"The report should be submitted ___ Friday.",choices:["until","by","since","during"],ans:1,exp:"「〜までに」という期限を表す by が正解。",cat:"前置詞"},
  {id:23,q:"The meeting room is located ___ the third floor.",choices:["in","on","at","to"],ans:1,exp:"階を表す場合は on を使う（on the third floor）。",cat:"前置詞"},
  {id:24,q:"She has worked here ___ five years.",choices:["since","for","from","during"],ans:1,exp:"期間を表す場合は for（for five years）。",cat:"前置詞"},
  {id:25,q:"The package was delivered ___ the customer's request.",choices:["according to","along with","in spite of","instead of"],ans:0,exp:"「〜に従って」は according to。",cat:"前置詞"},
  {id:26,q:"All visitors must check in ___ the reception desk.",choices:["at","in","on","to"],ans:0,exp:"特定の地点（受付）には at を使う。",cat:"前置詞"},
  {id:27,q:"The factory operates ___ a strict safety protocol.",choices:["under","over","above","beyond"],ans:0,exp:"「〜のもとで」は under。under a strict protocol。",cat:"前置詞"},
  {id:28,q:"The negotiations continued ___ midnight.",choices:["until","by","at","on"],ans:0,exp:"「〜まで（継続）」は until。",cat:"前置詞"},
  {id:29,q:"The new policy applies ___ all departments.",choices:["to","for","with","of"],ans:0,exp:"apply to ~ で「〜に適用される」。",cat:"前置詞"},
  {id:30,q:"He was praised ___ his excellent performance.",choices:["for","to","with","by"],ans:0,exp:"praise A for B「BのことでAを称賛する」。",cat:"前置詞"},
  // 関係詞
  {id:31,q:"The employee ___ proposal was accepted received an award.",choices:["who","whose","which","whom"],ans:1,exp:"後ろに名詞（proposal）が続く所有格の関係代名詞 whose が正解。",cat:"関係詞"},
  {id:32,q:"This is the product ___ we have been developing.",choices:["who","whose","which","where"],ans:2,exp:"物（product）を先行詞とする関係代名詞は which。",cat:"関係詞"},
  {id:33,q:"The manager ___ approved the budget is on vacation.",choices:["which","who","whom","whose"],ans:1,exp:"人（manager）を先行詞とし主語の働きをする関係代名詞は who。",cat:"関係詞"},
  {id:34,q:"This is the office ___ I work.",choices:["which","where","who","whose"],ans:1,exp:"場所を表す先行詞には関係副詞 where。",cat:"関係詞"},
  {id:35,q:"The reason ___ she resigned remains unclear.",choices:["why","which","who","where"],ans:0,exp:"理由を表す先行詞 reason には関係副詞 why。",cat:"関係詞"},
  // 接続詞
  {id:36,q:"___ the rain, the event was held outdoors.",choices:["Despite","Although","Because","Even"],ans:0,exp:"後ろに名詞句が続くので前置詞 despite が正解。",cat:"接続詞"},
  {id:37,q:"___ it was raining, the event was held outdoors.",choices:["Despite","In spite of","Although","Because of"],ans:2,exp:"後ろにSV（節）が続くので接続詞 although が正解。",cat:"接続詞"},
  {id:38,q:"The store will remain open ___ the holiday.",choices:["during","while","when","as"],ans:0,exp:"後ろに名詞句が続くので前置詞 during が正解。",cat:"接続詞"},
  {id:39,q:"You should call the office ___ you have any questions.",choices:["if","despite","because of","during"],ans:0,exp:"条件を表す接続詞 if が正解。",cat:"接続詞"},
  {id:40,q:"___ the budget is limited, the team did excellent work.",choices:["Because","Even though","Due to","Despite"],ans:1,exp:"後ろに節が続き、逆接の意味になるのは even though。",cat:"接続詞"},
  // 比較
  {id:41,q:"This model is ___ than the previous one.",choices:["efficient","more efficient","most efficient","efficiently"],ans:1,exp:"than があるので比較級 more efficient が正解。",cat:"比較"},
  {id:42,q:"This is the ___ option among all the choices.",choices:["good","better","best","well"],ans:2,exp:"the と among all があるので最上級 best が正解。",cat:"比較"},
  {id:43,q:"The new model runs ___ as quietly as the old one.",choices:["so","as","more","most"],ans:1,exp:"as ~ as の同等比較構文。",cat:"比較"},
  {id:44,q:"Sales this quarter were ___ higher than expected.",choices:["very","much","so","too"],ans:1,exp:"比較級を強調する語は much。",cat:"比較"},
  {id:45,q:"The more you practice, the ___ you become.",choices:["good","well","better","best"],ans:2,exp:"the more ~ the 比較級 の構文。",cat:"比較"},
  // 仮定法・態
  {id:46,q:"If the budget ___ approved, we would start the project immediately.",choices:["is","was","were","be"],ans:2,exp:"仮定法過去では be動詞は were を使う（If S were ~）。",cat:"仮定法"},
  {id:47,q:"The report ___ by the accounting team every month.",choices:["prepares","is prepared","prepared","preparing"],ans:1,exp:"主語 report は「準備される」側なので受動態 is prepared。",cat:"態"},
  {id:48,q:"The new factory ___ next year.",choices:["will build","will be built","builds","is building"],ans:1,exp:"factory は「建てられる」側なので受動態 will be built。",cat:"態"},
  {id:49,q:"If I ___ you, I would accept the offer.",choices:["am","was","were","be"],ans:2,exp:"仮定法過去の定型表現 If I were you。",cat:"仮定法"},
  {id:50,q:"The documents ___ carefully before signing.",choices:["should review","should be reviewed","reviews","reviewing"],ans:1,exp:"documents は「見直される」側なので受動態 should be reviewed。",cat:"態"},
];
