// TOEIC600点対策 頻出単語データ（カテゴリ別）
const VOCAB_DATA = [
  // ===== ビジネス一般 =====
  {id:1,word:"approve",pos:"v",mean:"承認する",ex:"The manager approved the budget proposal.",exJa:"マネージャーは予算案を承認した。",cat:"business"},
  {id:2,word:"attach",pos:"v",mean:"添付する",ex:"Please attach your resume to the email.",exJa:"履歴書をメールに添付してください。",cat:"business"},
  {id:3,word:"budget",pos:"n",mean:"予算",ex:"We need to stay within budget.",exJa:"予算内に収める必要がある。",cat:"business"},
  {id:4,word:"colleague",pos:"n",mean:"同僚",ex:"She discussed the project with her colleague.",exJa:"彼女は同僚とそのプロジェクトについて話し合った。",cat:"business"},
  {id:5,word:"deadline",pos:"n",mean:"締め切り",ex:"The deadline for the report is Friday.",exJa:"報告書の締め切りは金曜日だ。",cat:"business"},
  {id:6,word:"department",pos:"n",mean:"部署",ex:"He transferred to the sales department.",exJa:"彼は営業部に異動した。",cat:"business"},
  {id:7,word:"employee",pos:"n",mean:"従業員",ex:"All employees must attend the meeting.",exJa:"全従業員が会議に出席しなければならない。",cat:"business"},
  {id:8,word:"invoice",pos:"n",mean:"請求書",ex:"Please send the invoice by email.",exJa:"請求書をメールで送ってください。",cat:"business"},
  {id:9,word:"negotiate",pos:"v",mean:"交渉する",ex:"They negotiated a better contract.",exJa:"彼らはより良い契約を交渉した。",cat:"business"},
  {id:10,word:"postpone",pos:"v",mean:"延期する",ex:"The meeting was postponed until next week.",exJa:"会議は来週まで延期された。",cat:"business"},
  {id:11,word:"promote",pos:"v",mean:"昇進させる",ex:"She was promoted to manager last year.",exJa:"彼女は昨年マネージャーに昇進した。",cat:"business"},
  {id:12,word:"reimburse",pos:"v",mean:"払い戻す",ex:"The company will reimburse travel expenses.",exJa:"会社は旅費を払い戻す。",cat:"business"},
  {id:13,word:"resign",pos:"v",mean:"辞職する",ex:"He decided to resign from his position.",exJa:"彼は職を辞することを決めた。",cat:"business"},
  {id:14,word:"salary",pos:"n",mean:"給料",ex:"Her salary increased after the promotion.",exJa:"昇進後、彼女の給料が上がった。",cat:"business"},
  {id:15,word:"supervisor",pos:"n",mean:"上司、監督者",ex:"Ask your supervisor for approval.",exJa:"承認は上司に求めてください。",cat:"business"},
  {id:16,word:"vacant",pos:"adj",mean:"空いている",ex:"There is a vacant position in marketing.",exJa:"マーケティング部に空きポジションがある。",cat:"business"},
  {id:17,word:"warehouse",pos:"n",mean:"倉庫",ex:"The goods are stored in the warehouse.",exJa:"商品は倉庫に保管されている。",cat:"business"},
  {id:18,word:"merger",pos:"n",mean:"合併",ex:"The merger created a larger company.",exJa:"その合併でより大きな会社が誕生した。",cat:"business"},
  {id:19,word:"revenue",pos:"n",mean:"収益",ex:"Revenue increased by 10% this quarter.",exJa:"今四半期、収益は10%増加した。",cat:"business"},
  {id:20,word:"expense",pos:"n",mean:"経費",ex:"Travel expenses must be reported.",exJa:"旅費は報告しなければならない。",cat:"business"},
  {id:21,word:"shareholder",pos:"n",mean:"株主",ex:"Shareholders attended the annual meeting.",exJa:"株主たちは年次総会に出席した。",cat:"business"},
  {id:22,word:"subsidiary",pos:"n",mean:"子会社",ex:"The subsidiary operates independently.",exJa:"その子会社は独立して運営されている。",cat:"business"},
  {id:23,word:"headquarters",pos:"n",mean:"本社",ex:"The headquarters is located in Tokyo.",exJa:"本社は東京にある。",cat:"business"},
  {id:24,word:"recruit",pos:"v",mean:"採用する",ex:"The company plans to recruit new staff.",exJa:"会社は新しいスタッフを採用する予定だ。",cat:"business"},
  {id:25,word:"qualification",pos:"n",mean:"資格",ex:"She has the qualifications for the job.",exJa:"彼女はその仕事に必要な資格を持っている。",cat:"business"},
  {id:26,word:"candidate",pos:"n",mean:"候補者",ex:"Three candidates applied for the position.",exJa:"3名の候補者がそのポジションに応募した。",cat:"business"},
  {id:27,word:"applicant",pos:"n",mean:"応募者",ex:"The applicant submitted her resume online.",exJa:"応募者はオンラインで履歴書を提出した。",cat:"business"},
  {id:28,word:"performance",pos:"n",mean:"業績、成果",ex:"His performance review is next month.",exJa:"彼の業績評価は来月だ。",cat:"business"},
  {id:29,word:"productivity",pos:"n",mean:"生産性",ex:"New equipment improved productivity.",exJa:"新しい設備が生産性を向上させた。",cat:"business"},
  {id:30,word:"efficient",pos:"adj",mean:"効率的な",ex:"This is a more efficient method.",exJa:"これはより効率的な方法だ。",cat:"business"},
  // ===== オフィス・事務 =====
  {id:31,word:"agenda",pos:"n",mean:"議題",ex:"Please review the agenda before the meeting.",exJa:"会議前に議題を確認してください。",cat:"office"},
  {id:32,word:"draft",pos:"n",mean:"草案",ex:"He wrote the first draft of the report.",exJa:"彼は報告書の初稿を書いた。",cat:"office"},
  {id:33,word:"file",pos:"v",mean:"提出する、ファイルする",ex:"Please file the documents by Friday.",exJa:"金曜日までに書類を提出してください。",cat:"office"},
  {id:34,word:"forward",pos:"v",mean:"転送する",ex:"I will forward your email to the team.",exJa:"あなたのメールをチームに転送します。",cat:"office"},
  {id:35,word:"memo",pos:"n",mean:"メモ、覚書",ex:"She sent a memo to all staff.",exJa:"彼女は全スタッフにメモを送った。",cat:"office"},
  {id:36,word:"notify",pos:"v",mean:"通知する",ex:"We will notify you of any changes.",exJa:"変更があれば通知します。",cat:"office"},
  {id:37,word:"photocopy",pos:"v",mean:"コピーする",ex:"Could you photocopy this document?",exJa:"この書類をコピーしてもらえますか。",cat:"office"},
  {id:38,word:"reception",pos:"n",mean:"受付",ex:"Please check in at the reception desk.",exJa:"受付でチェックインしてください。",cat:"office"},
  {id:39,word:"stationery",pos:"n",mean:"文房具",ex:"We ordered new stationery for the office.",exJa:"オフィス用に新しい文房具を注文した。",cat:"office"},
  {id:40,word:"submit",pos:"v",mean:"提出する",ex:"Submit your application by the deadline.",exJa:"締め切りまでに申込書を提出してください。",cat:"office"},
  {id:41,word:"attendance",pos:"n",mean:"出席",ex:"Attendance at the seminar is mandatory.",exJa:"セミナーへの出席は必須だ。",cat:"office"},
  {id:42,word:"confirm",pos:"v",mean:"確認する",ex:"Please confirm your reservation.",exJa:"予約を確認してください。",cat:"office"},
  {id:43,word:"renew",pos:"v",mean:"更新する",ex:"We need to renew the contract.",exJa:"契約を更新する必要がある。",cat:"office"},
  {id:44,word:"revise",pos:"v",mean:"改訂する",ex:"Please revise the document before sending.",exJa:"送る前に文書を改訂してください。",cat:"office"},
  {id:45,word:"distribute",pos:"v",mean:"配布する",ex:"Handouts were distributed to everyone.",exJa:"配布資料は全員に配られた。",cat:"office"},
  // ===== 会議・コミュニケーション =====
  {id:46,word:"conference",pos:"n",mean:"会議",ex:"The annual conference will be held in March.",exJa:"年次会議は3月に開催される。",cat:"meeting"},
  {id:47,word:"presentation",pos:"n",mean:"発表",ex:"She gave a presentation on the new product.",exJa:"彼女は新製品についての発表をした。",cat:"meeting"},
  {id:48,word:"participant",pos:"n",mean:"参加者",ex:"All participants received a certificate.",exJa:"参加者全員が証明書を受け取った。",cat:"meeting"},
  {id:49,word:"venue",pos:"n",mean:"会場",ex:"The venue for the conference has changed.",exJa:"会議の会場が変更になった。",cat:"meeting"},
  {id:50,word:"reschedule",pos:"v",mean:"予定を変更する",ex:"We had to reschedule the meeting.",exJa:"会議の予定を変更する必要があった。",cat:"meeting"},
  {id:51,word:"discuss",pos:"v",mean:"議論する",ex:"Let's discuss this issue further.",exJa:"この問題についてさらに議論しましょう。",cat:"meeting"},
  {id:52,word:"feedback",pos:"n",mean:"フィードバック",ex:"We appreciate your feedback on the survey.",exJa:"アンケートへのフィードバックに感謝します。",cat:"meeting"},
  {id:53,word:"clarify",pos:"v",mean:"明確にする",ex:"Could you clarify your point?",exJa:"あなたの論点を明確にしてもらえますか。",cat:"meeting"},
  {id:54,word:"brief",pos:"v",mean:"説明する",ex:"He briefed the team on the new policy.",exJa:"彼はチームに新方針について説明した。",cat:"meeting"},
  {id:55,word:"consensus",pos:"n",mean:"合意",ex:"The team reached a consensus.",exJa:"チームは合意に達した。",cat:"meeting"},
  // ===== 出張・旅行 =====
  {id:56,word:"itinerary",pos:"n",mean:"旅程",ex:"Here is the itinerary for your trip.",exJa:"こちらが旅行の旅程です。",cat:"travel"},
  {id:57,word:"departure",pos:"n",mean:"出発",ex:"The departure time was delayed.",exJa:"出発時刻が遅れた。",cat:"travel"},
  {id:58,word:"arrival",pos:"n",mean:"到着",ex:"Please check the arrival gate.",exJa:"到着ゲートを確認してください。",cat:"travel"},
  {id:59,word:"luggage",pos:"n",mean:"荷物",ex:"Please keep your luggage with you.",exJa:"荷物は手元に置いておいてください。",cat:"travel"},
  {id:60,word:"boarding",pos:"n",mean:"搭乗",ex:"Boarding will begin in ten minutes.",exJa:"搭乗は10分後に始まる。",cat:"travel"},
  {id:61,word:"accommodation",pos:"n",mean:"宿泊施設",ex:"We arranged accommodation near the airport.",exJa:"空港近くに宿泊施設を手配した。",cat:"travel"},
  {id:62,word:"reservation",pos:"n",mean:"予約",ex:"I made a reservation for two nights.",exJa:"2泊の予約をした。",cat:"travel"},
  {id:63,word:"fare",pos:"n",mean:"運賃",ex:"The train fare has increased.",exJa:"電車の運賃が上がった。",cat:"travel"},
  {id:64,word:"destination",pos:"n",mean:"目的地",ex:"Our final destination is Osaka.",exJa:"最終目的地は大阪だ。",cat:"travel"},
  {id:65,word:"delay",pos:"n",mean:"遅延",ex:"The flight delay was due to weather.",exJa:"フライトの遅延は天候のためだった。",cat:"travel"},
  // ===== 店舗・小売 =====
  {id:66,word:"merchandise",pos:"n",mean:"商品",ex:"New merchandise arrived this morning.",exJa:"新しい商品が今朝届いた。",cat:"retail"},
  {id:67,word:"discount",pos:"n",mean:"割引",ex:"Customers received a 20% discount.",exJa:"顧客は20%の割引を受けた。",cat:"retail"},
  {id:68,word:"refund",pos:"n",mean:"返金",ex:"You can request a refund within 30 days.",exJa:"30日以内なら返金を申請できる。",cat:"retail"},
  {id:69,word:"warranty",pos:"n",mean:"保証",ex:"The product comes with a one-year warranty.",exJa:"その製品には1年保証が付いている。",cat:"retail"},
  {id:70,word:"inventory",pos:"n",mean:"在庫",ex:"We need to check the inventory.",exJa:"在庫を確認する必要がある。",cat:"retail"},
  {id:71,word:"purchase",pos:"v",mean:"購入する",ex:"She purchased a new laptop.",exJa:"彼女は新しいノートパソコンを購入した。",cat:"retail"},
  {id:72,word:"receipt",pos:"n",mean:"領収書",ex:"Keep your receipt for returns.",exJa:"返品のために領収書を保管してください。",cat:"retail"},
  {id:73,word:"exchange",pos:"v",mean:"交換する",ex:"You can exchange the item for a different size.",exJa:"商品を別のサイズに交換できる。",cat:"retail"},
  {id:74,word:"display",pos:"n",mean:"陳列、展示",ex:"The products are on display in the window.",exJa:"商品はショーウィンドウに展示されている。",cat:"retail"},
  {id:75,word:"retailer",pos:"n",mean:"小売業者",ex:"The retailer offers free shipping.",exJa:"その小売業者は送料無料を提供している。",cat:"retail"},
  // ===== 製造・物流 =====
  {id:76,word:"manufacture",pos:"v",mean:"製造する",ex:"The factory manufactures car parts.",exJa:"その工場は車の部品を製造している。",cat:"manufacturing"},
  {id:77,word:"shipment",pos:"n",mean:"出荷、輸送",ex:"The shipment arrived on time.",exJa:"その出荷は時間通りに到着した。",cat:"manufacturing"},
  {id:78,word:"defect",pos:"n",mean:"欠陥",ex:"The product had a minor defect.",exJa:"その製品には小さな欠陥があった。",cat:"manufacturing"},
  {id:79,word:"durable",pos:"adj",mean:"耐久性のある",ex:"This material is very durable.",exJa:"この素材はとても耐久性がある。",cat:"manufacturing"},
  {id:80,word:"assemble",pos:"v",mean:"組み立てる",ex:"Workers assemble the parts on the line.",exJa:"作業員はラインで部品を組み立てる。",cat:"manufacturing"},
  {id:81,word:"supplier",pos:"n",mean:"供給業者",ex:"We changed our supplier last month.",exJa:"先月、供給業者を変更した。",cat:"manufacturing"},
  {id:82,word:"quality control",pos:"n",mean:"品質管理",ex:"Quality control is essential in manufacturing.",exJa:"品質管理は製造業において不可欠だ。",cat:"manufacturing"},
  {id:83,word:"maintenance",pos:"n",mean:"保守、メンテナンス",ex:"Regular maintenance prevents breakdowns.",exJa:"定期的な保守は故障を防ぐ。",cat:"manufacturing"},
  {id:84,word:"equipment",pos:"n",mean:"設備、機器",ex:"New equipment was installed last week.",exJa:"先週、新しい設備が設置された。",cat:"manufacturing"},
  {id:85,word:"facility",pos:"n",mean:"施設",ex:"The company built a new facility.",exJa:"会社は新しい施設を建設した。",cat:"manufacturing"},
  // ===== 形容詞・副詞（頻出） =====
  {id:86,word:"available",pos:"adj",mean:"利用可能な",ex:"The manager is not available right now.",exJa:"マネージャーは今、対応できません。",cat:"adj"},
  {id:87,word:"reliable",pos:"adj",mean:"信頼できる",ex:"We need a reliable supplier.",exJa:"信頼できる供給業者が必要だ。",cat:"adj"},
  {id:88,word:"essential",pos:"adj",mean:"不可欠な",ex:"Teamwork is essential for success.",exJa:"成功にはチームワークが不可欠だ。",cat:"adj"},
  {id:89,word:"approximately",pos:"adv",mean:"おおよそ",ex:"The trip takes approximately two hours.",exJa:"その旅は約2時間かかる。",cat:"adj"},
  {id:90,word:"frequently",pos:"adv",mean:"頻繁に",ex:"He frequently travels for business.",exJa:"彼は頻繁に出張する。",cat:"adj"},
  {id:91,word:"considerably",pos:"adv",mean:"かなり",ex:"Sales increased considerably this year.",exJa:"今年、売上はかなり増加した。",cat:"adj"},
  {id:92,word:"thoroughly",pos:"adv",mean:"徹底的に",ex:"Please review the contract thoroughly.",exJa:"契約書を徹底的に確認してください。",cat:"adj"},
  {id:93,word:"immediately",pos:"adv",mean:"すぐに",ex:"Please respond immediately.",exJa:"すぐに返信してください。",cat:"adj"},
  {id:94,word:"voluntarily",pos:"adv",mean:"自発的に",ex:"He volunteered to help voluntarily.",exJa:"彼は自発的に手伝うことを申し出た。",cat:"adj"},
  {id:95,word:"significantly",pos:"adv",mean:"著しく",ex:"Costs decreased significantly.",exJa:"コストは著しく減少した。",cat:"adj"},
  {id:96,word:"competent",pos:"adj",mean:"有能な",ex:"She is a competent manager.",exJa:"彼女は有能なマネージャーだ。",cat:"adj"},
  {id:97,word:"flexible",pos:"adj",mean:"柔軟な",ex:"We offer flexible working hours.",exJa:"弊社は柔軟な勤務時間を提供している。",cat:"adj"},
  {id:98,word:"mandatory",pos:"adj",mean:"義務的な",ex:"Attendance is mandatory for all staff.",exJa:"出席は全スタッフにとって義務だ。",cat:"adj"},
  {id:99,word:"comprehensive",pos:"adj",mean:"包括的な",ex:"This is a comprehensive guide.",exJa:"これは包括的なガイドだ。",cat:"adj"},
  {id:100,word:"outstanding",pos:"adj",mean:"未払いの／傑出した",ex:"There is an outstanding balance on your account.",exJa:"あなたの口座には未払い残高がある。",cat:"adj"},
  // ===== 動詞（頻出） =====
  {id:101,word:"accomplish",pos:"v",mean:"成し遂げる",ex:"We accomplished our sales goal.",exJa:"私たちは売上目標を達成した。",cat:"verb"},
  {id:102,word:"acquire",pos:"v",mean:"取得する",ex:"The company acquired a smaller firm.",exJa:"その会社は小さな会社を買収した。",cat:"verb"},
  {id:103,word:"address",pos:"v",mean:"対処する",ex:"We need to address this problem.",exJa:"この問題に対処する必要がある。",cat:"verb"},
  {id:104,word:"allocate",pos:"v",mean:"割り当てる",ex:"Funds were allocated for research.",exJa:"資金は研究のために割り当てられた。",cat:"verb"},
  {id:105,word:"announce",pos:"v",mean:"発表する",ex:"They announced a new product line.",exJa:"彼らは新製品ラインを発表した。",cat:"verb"},
  {id:106,word:"authorize",pos:"v",mean:"許可する",ex:"Only managers can authorize refunds.",exJa:"返金を許可できるのはマネージャーのみだ。",cat:"verb"},
  {id:107,word:"calculate",pos:"v",mean:"計算する",ex:"Please calculate the total cost.",exJa:"総費用を計算してください。",cat:"verb"},
  {id:108,word:"cancel",pos:"v",mean:"中止する",ex:"The flight was cancelled due to weather.",exJa:"フライトは天候のため中止された。",cat:"verb"},
  {id:109,word:"complete",pos:"v",mean:"完了する",ex:"Please complete the form by Monday.",exJa:"月曜日までにフォームを完成させてください。",cat:"verb"},
  {id:110,word:"contribute",pos:"v",mean:"貢献する",ex:"Everyone contributed to the project.",exJa:"全員がそのプロジェクトに貢献した。",cat:"verb"},
  {id:111,word:"determine",pos:"v",mean:"決定する",ex:"We will determine the budget next week.",exJa:"来週、予算を決定する。",cat:"verb"},
  {id:112,word:"establish",pos:"v",mean:"設立する",ex:"The company was established in 1990.",exJa:"その会社は1990年に設立された。",cat:"verb"},
  {id:113,word:"estimate",pos:"v",mean:"見積もる",ex:"We estimate the cost at $5,000.",exJa:"費用は5000ドルと見積もっている。",cat:"verb"},
  {id:114,word:"evaluate",pos:"v",mean:"評価する",ex:"Managers evaluate employee performance.",exJa:"マネージャーは従業員の業績を評価する。",cat:"verb"},
  {id:115,word:"expand",pos:"v",mean:"拡大する",ex:"The company plans to expand overseas.",exJa:"その会社は海外への拡大を計画している。",cat:"verb"},
  {id:116,word:"implement",pos:"v",mean:"実施する",ex:"We will implement the new policy next month.",exJa:"来月、新方針を実施する。",cat:"verb"},
  {id:117,word:"indicate",pos:"v",mean:"示す",ex:"The survey indicates strong customer satisfaction.",exJa:"調査は高い顧客満足度を示している。",cat:"verb"},
  {id:118,word:"launch",pos:"v",mean:"開始する",ex:"The company will launch a new app.",exJa:"その会社は新しいアプリを開始する。",cat:"verb"},
  {id:119,word:"maintain",pos:"v",mean:"維持する",ex:"It is important to maintain good relationships.",exJa:"良い関係を維持することは重要だ。",cat:"verb"},
  {id:120,word:"obtain",pos:"v",mean:"取得する",ex:"You must obtain permission first.",exJa:"まず許可を取得しなければならない。",cat:"verb"},
  {id:121,word:"occur",pos:"v",mean:"起こる",ex:"The error occurred during installation.",exJa:"そのエラーはインストール中に発生した。",cat:"verb"},
  {id:122,word:"prevent",pos:"v",mean:"防ぐ",ex:"This will prevent future problems.",exJa:"これにより将来の問題を防げる。",cat:"verb"},
  {id:123,word:"proceed",pos:"v",mean:"進める",ex:"Let's proceed with the plan.",exJa:"計画を進めましょう。",cat:"verb"},
  {id:124,word:"recommend",pos:"v",mean:"推薦する",ex:"I recommend this restaurant.",exJa:"このレストランをお勧めします。",cat:"verb"},
  {id:125,word:"reduce",pos:"v",mean:"減らす",ex:"We need to reduce costs.",exJa:"コストを削減する必要がある。",cat:"verb"},
  {id:126,word:"replace",pos:"v",mean:"交換する",ex:"The old machine was replaced.",exJa:"古い機械は交換された。",cat:"verb"},
  {id:127,word:"require",pos:"v",mean:"必要とする",ex:"This job requires experience.",exJa:"この仕事には経験が必要だ。",cat:"verb"},
  {id:128,word:"reveal",pos:"v",mean:"明らかにする",ex:"The report revealed new findings.",exJa:"その報告書は新たな発見を明らかにした。",cat:"verb"},
  {id:129,word:"specialize",pos:"v",mean:"専門にする",ex:"She specializes in marketing.",exJa:"彼女はマーケティングを専門にしている。",cat:"verb"},
  {id:130,word:"verify",pos:"v",mean:"確認する",ex:"Please verify your information.",exJa:"あなたの情報を確認してください。",cat:"verb"},
  // ===== 追加: ビジネス全般 =====
  {id:131,word:"proposal",pos:"n",mean:"提案書",ex:"The proposal was approved by the board.",exJa:"その提案書は取締役会で承認された。",cat:"business"},
  {id:132,word:"stakeholder",pos:"n",mean:"利害関係者",ex:"All stakeholders were informed of the decision.",exJa:"すべての利害関係者にその決定が伝えられた。",cat:"business"},
  {id:133,word:"strategy",pos:"n",mean:"戦略",ex:"The company adopted a new marketing strategy.",exJa:"その会社は新しいマーケティング戦略を採用した。",cat:"business"},
  {id:134,word:"outsource",pos:"v",mean:"外部委託する",ex:"They decided to outsource the IT support.",exJa:"彼らはITサポートを外部委託することにした。",cat:"business"},
  {id:135,word:"collaborate",pos:"v",mean:"協力する",ex:"Our team will collaborate with another department.",exJa:"私たちのチームは他部署と協力する。",cat:"business"},
  {id:136,word:"initiative",pos:"n",mean:"新たな取り組み",ex:"The company launched a sustainability initiative.",exJa:"その会社は持続可能性への取り組みを開始した。",cat:"business"},
  {id:137,word:"forecast",pos:"n",mean:"予測",ex:"The sales forecast looks promising.",exJa:"売上予測は有望に見える。",cat:"business"},
  {id:138,word:"benchmark",pos:"n",mean:"基準",ex:"We use industry benchmarks to measure performance.",exJa:"業績測定には業界基準を用いる。",cat:"business"},
  {id:139,word:"turnover",pos:"n",mean:"離職率／売上高",ex:"Employee turnover decreased this year.",exJa:"今年、従業員の離職率は下がった。",cat:"business"},
  {id:140,word:"downsize",pos:"v",mean:"人員削減する",ex:"The company had to downsize due to losses.",exJa:"会社は損失のため人員削減をしなければならなかった。",cat:"business"},
  // ===== 追加: オフィス・事務 =====
  {id:141,word:"correspondence",pos:"n",mean:"通信文、やり取り",ex:"Please keep a record of all correspondence.",exJa:"すべてのやり取りの記録を保管してください。",cat:"office"},
  {id:142,word:"draft",pos:"v",mean:"下書きする",ex:"She will draft the proposal by Friday.",exJa:"彼女は金曜日までに提案書の下書きをする。",cat:"office"},
  {id:143,word:"archive",pos:"v",mean:"保管する",ex:"Old files should be archived properly.",exJa:"古いファイルは適切に保管されるべきだ。",cat:"office"},
  {id:144,word:"proofread",pos:"v",mean:"校正する",ex:"Please proofread the document before printing.",exJa:"印刷前に文書を校正してください。",cat:"office"},
  {id:145,word:"itemize",pos:"v",mean:"項目別に示す",ex:"The invoice itemizes each charge.",exJa:"請求書は各料金を項目別に示している。",cat:"office"},
  {id:146,word:"paperwork",pos:"n",mean:"事務書類",ex:"There is a lot of paperwork to complete.",exJa:"完了させるべき事務書類がたくさんある。",cat:"office"},
  {id:147,word:"signature",pos:"n",mean:"署名",ex:"The contract requires your signature.",exJa:"契約書にはあなたの署名が必要だ。",cat:"office"},
  {id:148,word:"enclose",pos:"v",mean:"同封する",ex:"Please find the enclosed document.",exJa:"同封の書類をご確認ください。",cat:"office"},
  {id:149,word:"circulate",pos:"v",mean:"回覧する",ex:"The memo was circulated to all staff.",exJa:"そのメモは全スタッフに回覧された。",cat:"office"},
  {id:150,word:"deadline",pos:"n",mean:"締め切り（再掲・重要語）",ex:"We must meet the deadline this week.",exJa:"今週中に締め切りを守らなければならない。",cat:"office"},
  // ===== 追加: 会議 =====
  {id:151,word:"minutes",pos:"n",mean:"議事録",ex:"The minutes of the meeting were sent by email.",exJa:"会議の議事録がメールで送られた。",cat:"meeting"},
  {id:152,word:"moderator",pos:"n",mean:"司会者",ex:"The moderator introduced each speaker.",exJa:"司会者は各講演者を紹介した。",cat:"meeting"},
  {id:153,word:"keynote",pos:"n",mean:"基調講演",ex:"She delivered the keynote speech.",exJa:"彼女は基調講演を行った。",cat:"meeting"},
  {id:154,word:"attendee",pos:"n",mean:"出席者",ex:"Attendees received a name badge at the entrance.",exJa:"出席者は入口で名札を受け取った。",cat:"meeting"},
  {id:155,word:"proceedings",pos:"n",mean:"議事、成り行き",ex:"The proceedings were recorded for later review.",exJa:"議事は後で確認できるよう記録された。",cat:"meeting"},
  // ===== 追加: 出張・旅行 =====
  {id:156,word:"layover",pos:"n",mean:"乗り継ぎ",ex:"We have a two-hour layover in Seoul.",exJa:"ソウルで2時間の乗り継ぎがある。",cat:"travel"},
  {id:157,word:"itemized receipt",pos:"n",mean:"明細付き領収書",ex:"Please keep an itemized receipt for reimbursement.",exJa:"払い戻しのために明細付き領収書を保管してください。",cat:"travel"},
  {id:158,word:"customs",pos:"n",mean:"税関",ex:"We had to go through customs at the airport.",exJa:"空港で税関を通過しなければならなかった。",cat:"travel"},
  {id:159,word:"itinerary change",pos:"n",mean:"旅程変更",ex:"An itinerary change was necessary due to weather.",exJa:"天候のため旅程変更が必要だった。",cat:"travel"},
  {id:160,word:"complimentary",pos:"adj",mean:"無料の",ex:"The hotel offers a complimentary breakfast.",exJa:"そのホテルは無料の朝食を提供している。",cat:"travel"},
  {id:161,word:"concierge",pos:"n",mean:"コンシェルジュ",ex:"Ask the concierge for restaurant recommendations.",exJa:"レストランのおすすめはコンシェルジュに尋ねてください。",cat:"travel"},
  {id:162,word:"nonrefundable",pos:"adj",mean:"払い戻し不可の",ex:"This ticket is nonrefundable.",exJa:"このチケットは払い戻し不可だ。",cat:"travel"},
  {id:163,word:"transit",pos:"n",mean:"乗り継ぎ、輸送",ex:"Passengers in transit should stay in the lounge.",exJa:"乗り継ぎ客はラウンジで待機してください。",cat:"travel"},
  {id:164,word:"itinerary",pos:"n",mean:"旅程（重要語再掲）",ex:"Check your itinerary before departure.",exJa:"出発前に旅程を確認してください。",cat:"travel"},
  {id:165,word:"overbooked",pos:"adj",mean:"予約超過の",ex:"The flight was overbooked, so some passengers were rebooked.",exJa:"フライトは予約超過だったため、一部の乗客は振替となった。",cat:"travel"},
  // ===== 追加: 店舗・小売 =====
  {id:166,word:"clearance",pos:"n",mean:"在庫一掃セール",ex:"The store is having a clearance sale this weekend.",exJa:"その店は今週末在庫一掃セールを行う。",cat:"retail"},
  {id:167,word:"loyalty program",pos:"n",mean:"会員プログラム",ex:"Join our loyalty program to earn points.",exJa:"ポイントを貯めるには会員プログラムにご登録ください。",cat:"retail"},
  {id:168,word:"markdown",pos:"n",mean:"値下げ",ex:"There was a markdown on winter clothing.",exJa:"冬物衣料に値下げがあった。",cat:"retail"},
  {id:169,word:"checkout",pos:"n",mean:"レジ、会計",ex:"Please proceed to the checkout counter.",exJa:"レジカウンターへお進みください。",cat:"retail"},
  {id:170,word:"out of stock",pos:"adj",mean:"在庫切れ",ex:"This item is currently out of stock.",exJa:"この商品は現在在庫切れです。",cat:"retail"},
  {id:171,word:"bulk",pos:"adj",mean:"大量の",ex:"Buying in bulk saves money.",exJa:"まとめ買いはお金の節約になる。",cat:"retail"},
  {id:172,word:"vendor",pos:"n",mean:"販売業者",ex:"We negotiated a discount with the vendor.",exJa:"私たちは販売業者と割引交渉をした。",cat:"retail"},
  {id:173,word:"storefront",pos:"n",mean:"店頭",ex:"The storefront was redesigned last month.",exJa:"店頭は先月改装された。",cat:"retail"},
  {id:174,word:"price tag",pos:"n",mean:"値札",ex:"Check the price tag before purchasing.",exJa:"購入前に値札を確認してください。",cat:"retail"},
  {id:175,word:"consignment",pos:"n",mean:"委託販売",ex:"The shop sells items on consignment.",exJa:"その店は委託販売で商品を売っている。",cat:"retail"},
  // ===== 追加: 製造・物流 =====
  {id:176,word:"logistics",pos:"n",mean:"物流",ex:"The logistics team handles all shipments.",exJa:"物流チームがすべての出荷を管理する。",cat:"manufacturing"},
  {id:177,word:"assembly line",pos:"n",mean:"組立ライン",ex:"Workers on the assembly line wear protective gear.",exJa:"組立ラインの作業員は防護具を着用する。",cat:"manufacturing"},
  {id:178,word:"raw material",pos:"n",mean:"原材料",ex:"Raw material prices have risen recently.",exJa:"原材料価格は最近上昇している。",cat:"manufacturing"},
  {id:179,word:"output",pos:"n",mean:"生産高",ex:"Factory output increased by 15 percent.",exJa:"工場の生産高は15%増加した。",cat:"manufacturing"},
  {id:180,word:"inspect",pos:"v",mean:"検査する",ex:"Each product is inspected before shipping.",exJa:"各製品は出荷前に検査される。",cat:"manufacturing"},
  {id:181,word:"packaging",pos:"n",mean:"梱包",ex:"The packaging was damaged during transit.",exJa:"梱包は輸送中に破損した。",cat:"manufacturing"},
  {id:182,word:"warranty claim",pos:"n",mean:"保証請求",ex:"Customers can submit a warranty claim online.",exJa:"顧客はオンラインで保証請求を提出できる。",cat:"manufacturing"},
  {id:183,word:"downtime",pos:"n",mean:"稼働停止時間",ex:"Scheduled downtime is required for maintenance.",exJa:"保守のため計画的な稼働停止時間が必要だ。",cat:"manufacturing"},
  {id:184,word:"streamline",pos:"v",mean:"効率化する",ex:"The new system streamlined production.",exJa:"新システムは生産を効率化した。",cat:"manufacturing"},
  {id:185,word:"bulk order",pos:"n",mean:"大口注文",ex:"We received a bulk order from a new client.",exJa:"新規顧客から大口注文を受けた。",cat:"manufacturing"},
  // ===== 新カテゴリ: 財務・会計 =====
  {id:186,word:"asset",pos:"n",mean:"資産",ex:"The company's assets increased last year.",exJa:"その会社の資産は昨年増加した。",cat:"finance"},
  {id:187,word:"liability",pos:"n",mean:"負債",ex:"The report lists all current liabilities.",exJa:"その報告書はすべての現在の負債を記載している。",cat:"finance"},
  {id:188,word:"audit",pos:"n",mean:"監査",ex:"An external audit is conducted annually.",exJa:"外部監査は毎年実施される。",cat:"finance"},
  {id:189,word:"fiscal year",pos:"n",mean:"会計年度",ex:"The fiscal year ends in March.",exJa:"会計年度は3月に終わる。",cat:"finance"},
  {id:190,word:"dividend",pos:"n",mean:"配当金",ex:"Shareholders received a dividend this quarter.",exJa:"株主は今四半期配当金を受け取った。",cat:"finance"},
  {id:191,word:"interest rate",pos:"n",mean:"金利",ex:"The interest rate remained unchanged.",exJa:"金利は変わらなかった。",cat:"finance"},
  {id:192,word:"depreciation",pos:"n",mean:"減価償却",ex:"Depreciation is calculated annually.",exJa:"減価償却は毎年計算される。",cat:"finance"},
  {id:193,word:"transaction",pos:"n",mean:"取引",ex:"All transactions are recorded electronically.",exJa:"すべての取引は電子的に記録される。",cat:"finance"},
  {id:194,word:"surplus",pos:"n",mean:"黒字、余剰",ex:"The company reported a budget surplus.",exJa:"その会社は予算の黒字を報告した。",cat:"finance"},
  {id:195,word:"deficit",pos:"n",mean:"赤字",ex:"The department is operating at a deficit.",exJa:"その部門は赤字で運営されている。",cat:"finance"},
  {id:196,word:"installment",pos:"n",mean:"分割払い",ex:"You can pay in monthly installments.",exJa:"毎月の分割払いが可能だ。",cat:"finance"},
  {id:197,word:"accrue",pos:"v",mean:"発生する、積み重なる",ex:"Interest accrues monthly on the account.",exJa:"その口座には毎月利息が発生する。",cat:"finance"},
  {id:198,word:"underwrite",pos:"v",mean:"保証する、引き受ける",ex:"The bank agreed to underwrite the loan.",exJa:"銀行はその融資を引き受けることに同意した。",cat:"finance"},
  {id:199,word:"portfolio",pos:"n",mean:"資産構成",ex:"Diversifying your portfolio reduces risk.",exJa:"資産構成を多様化するとリスクが減る。",cat:"finance"},
  {id:200,word:"appraisal",pos:"n",mean:"査定、評価",ex:"An appraisal of the property was conducted.",exJa:"その不動産の査定が行われた。",cat:"finance"},
  {id:201,word:"levy",pos:"v",mean:"課す",ex:"A tax is levied on imported goods.",exJa:"輸入品には税金が課される。",cat:"finance"},
  {id:202,word:"disburse",pos:"v",mean:"支払う、支出する",ex:"Funds will be disbursed next week.",exJa:"資金は来週支払われる。",cat:"finance"},
  {id:203,word:"ledger",pos:"n",mean:"帳簿",ex:"All expenses are recorded in the ledger.",exJa:"すべての経費は帳簿に記録される。",cat:"finance"},
  {id:204,word:"solvent",pos:"adj",mean:"支払い能力のある",ex:"The company remains solvent despite losses.",exJa:"損失にもかかわらずその会社は支払い能力を維持している。",cat:"finance"},
  {id:205,word:"appreciate",pos:"v",mean:"（価値が）上がる",ex:"The value of the property appreciated over time.",exJa:"その不動産の価値は時間とともに上昇した。",cat:"finance"},
  // ===== 新カテゴリ: IT・技術 =====
  {id:206,word:"upgrade",pos:"v",mean:"アップグレードする",ex:"We need to upgrade our software.",exJa:"ソフトウェアをアップグレードする必要がある。",cat:"it"},
  {id:207,word:"install",pos:"v",mean:"インストールする",ex:"Please install the latest update.",exJa:"最新のアップデートをインストールしてください。",cat:"it"},
  {id:208,word:"troubleshoot",pos:"v",mean:"問題を解決する",ex:"The technician helped troubleshoot the issue.",exJa:"技術者が問題解決を手伝った。",cat:"it"},
  {id:209,word:"backup",pos:"n",mean:"バックアップ",ex:"Always keep a backup of important files.",exJa:"重要なファイルは常にバックアップを取ってください。",cat:"it"},
  {id:210,word:"firewall",pos:"n",mean:"ファイアウォール",ex:"The firewall blocks unauthorized access.",exJa:"ファイアウォールは不正アクセスを防ぐ。",cat:"it"},
  {id:211,word:"bandwidth",pos:"n",mean:"帯域幅",ex:"The office needs more bandwidth for video calls.",exJa:"オフィスにはビデオ通話のためのより多くの帯域幅が必要だ。",cat:"it"},
  {id:212,word:"password protected",pos:"adj",mean:"パスワード保護された",ex:"The file is password protected.",exJa:"そのファイルはパスワードで保護されている。",cat:"it"},
  {id:213,word:"database",pos:"n",mean:"データベース",ex:"Customer information is stored in a database.",exJa:"顧客情報はデータベースに保管されている。",cat:"it"},
  {id:214,word:"glitch",pos:"n",mean:"不具合",ex:"A software glitch delayed the launch.",exJa:"ソフトウェアの不具合がローンチを遅らせた。",cat:"it"},
  {id:215,word:"server",pos:"n",mean:"サーバー",ex:"The server went down for an hour.",exJa:"サーバーが1時間ダウンした。",cat:"it"},
  {id:216,word:"compatible",pos:"adj",mean:"互換性のある",ex:"This device is compatible with most systems.",exJa:"この機器はほとんどのシステムと互換性がある。",cat:"it"},
  {id:217,word:"encrypt",pos:"v",mean:"暗号化する",ex:"All data is encrypted for security.",exJa:"すべてのデータはセキュリティのため暗号化される。",cat:"it"},
  {id:218,word:"login credentials",pos:"n",mean:"ログイン情報",ex:"Do not share your login credentials.",exJa:"ログイン情報を他人と共有しないでください。",cat:"it"},
  {id:219,word:"malfunction",pos:"v",mean:"故障する",ex:"The printer malfunctioned this morning.",exJa:"今朝プリンターが故障した。",cat:"it"},
  {id:220,word:"interface",pos:"n",mean:"インターフェース",ex:"The new interface is more user-friendly.",exJa:"新しいインターフェースはより使いやすい。",cat:"it"},
  // ===== 新カテゴリ: 人事・採用 =====
  {id:221,word:"onboarding",pos:"n",mean:"新入社員研修",ex:"The onboarding process takes one week.",exJa:"新入社員研修は1週間かかる。",cat:"hr"},
  {id:222,word:"probation period",pos:"n",mean:"試用期間",ex:"New hires undergo a three-month probation period.",exJa:"新入社員は3ヶ月の試用期間を経る。",cat:"hr"},
  {id:223,word:"benefits package",pos:"n",mean:"福利厚生",ex:"The company offers an excellent benefits package.",exJa:"その会社は優れた福利厚生を提供している。",cat:"hr"},
  {id:224,word:"terminate",pos:"v",mean:"解雇する",ex:"His contract was terminated early.",exJa:"彼の契約は早期に解除された。",cat:"hr"},
  {id:225,word:"appraisal interview",pos:"n",mean:"評価面談",ex:"Employees have an appraisal interview twice a year.",exJa:"従業員は年に2回評価面談を受ける。",cat:"hr"},
  {id:226,word:"headhunt",pos:"v",mean:"引き抜く",ex:"She was headhunted by a rival firm.",exJa:"彼女はライバル企業に引き抜かれた。",cat:"hr"},
  {id:227,word:"job posting",pos:"n",mean:"求人情報",ex:"The job posting attracted many applicants.",exJa:"その求人情報は多くの応募者を引きつけた。",cat:"hr"},
  {id:228,word:"seniority",pos:"n",mean:"勤続年数、年功",ex:"Promotions are partly based on seniority.",exJa:"昇進は部分的に勤続年数に基づいている。",cat:"hr"},
  {id:229,word:"paid leave",pos:"n",mean:"有給休暇",ex:"Employees are entitled to paid leave.",exJa:"従業員は有給休暇を取得する権利がある。",cat:"hr"},
  {id:230,word:"orientation",pos:"n",mean:"新人研修、オリエンテーション",ex:"New employees attend an orientation session.",exJa:"新入社員はオリエンテーションに参加する。",cat:"hr"},
  {id:231,word:"workforce",pos:"n",mean:"労働力、従業員全体",ex:"The company's workforce grew by 20 percent.",exJa:"その会社の従業員数は20%増加した。",cat:"hr"},
  {id:232,word:"severance pay",pos:"n",mean:"退職金",ex:"He received severance pay after the layoff.",exJa:"彼は解雇後に退職金を受け取った。",cat:"hr"},
  {id:233,word:"job description",pos:"n",mean:"職務内容",ex:"Please review the job description carefully.",exJa:"職務内容をよく確認してください。",cat:"hr"},
  {id:234,word:"screening",pos:"n",mean:"選考、審査",ex:"All candidates go through a screening process.",exJa:"すべての候補者は選考プロセスを経る。",cat:"hr"},
  {id:235,word:"tenure",pos:"n",mean:"在職期間",ex:"Her tenure at the company was ten years.",exJa:"彼女の在職期間は10年だった。",cat:"hr"},
  {id:236,word:"letter of recommendation",pos:"n",mean:"推薦状",ex:"He asked his professor for a letter of recommendation.",exJa:"彼は教授に推薦状を頼んだ。",cat:"hr"},
  {id:237,word:"skill set",pos:"n",mean:"スキルセット",ex:"She has a strong skill set in data analysis.",exJa:"彼女はデータ分析に強いスキルセットを持っている。",cat:"hr"},
  {id:238,word:"internship",pos:"n",mean:"インターンシップ",ex:"He completed an internship last summer.",exJa:"彼は昨夏インターンシップを終えた。",cat:"hr"},
  {id:239,word:"cover letter",pos:"n",mean:"添え状、カバーレター",ex:"Include a cover letter with your application.",exJa:"応募には添え状を添付してください。",cat:"hr"},
  {id:240,word:"personnel",pos:"n",mean:"人事、職員",ex:"Contact the personnel department for details.",exJa:"詳細は人事部にお問い合わせください。",cat:"hr"},
  // ===== 新カテゴリ: イベント・式典 =====
  {id:241,word:"banquet",pos:"n",mean:"晩餐会",ex:"The banquet will be held in the main hall.",exJa:"晩餐会はメインホールで開催される。",cat:"event"},
  {id:242,word:"ceremony",pos:"n",mean:"式典",ex:"The opening ceremony starts at nine.",exJa:"開会式は9時に始まる。",cat:"event"},
  {id:243,word:"RSVP",pos:"v",mean:"出欠を返事する",ex:"Please RSVP by next Monday.",exJa:"来週月曜日までに出欠のご返事をお願いします。",cat:"event"},
  {id:244,word:"host",pos:"v",mean:"主催する",ex:"The company will host a charity event.",exJa:"その会社はチャリティイベントを主催する。",cat:"event"},
  {id:245,word:"exhibit",pos:"n",mean:"展示",ex:"The trade show featured a new exhibit.",exJa:"見本市では新しい展示が行われた。",cat:"event"},
  {id:246,word:"sponsor",pos:"n",mean:"スポンサー",ex:"The event was funded by several sponsors.",exJa:"そのイベントは複数のスポンサーによって資金提供された。",cat:"event"},
  {id:247,word:"keynote speaker",pos:"n",mean:"基調講演者",ex:"The keynote speaker was well received.",exJa:"基調講演者は好評だった。",cat:"event"},
  {id:248,word:"turnout",pos:"n",mean:"参加者数、動員数",ex:"The turnout for the seminar exceeded expectations.",exJa:"セミナーの参加者数は予想を上回った。",cat:"event"},
  {id:249,word:"itinerary",pos:"n",mean:"式次第",ex:"The event itinerary was distributed in advance.",exJa:"イベントの式次第は事前に配布された。",cat:"event"},
  {id:250,word:"awards ceremony",pos:"n",mean:"表彰式",ex:"The awards ceremony recognized top performers.",exJa:"表彰式は優秀な社員を表彰した。",cat:"event"},
  {id:251,word:"venue capacity",pos:"n",mean:"会場収容人数",ex:"The venue capacity is limited to 200 people.",exJa:"会場収容人数は200人までに限られている。",cat:"event"},
  {id:252,word:"catering",pos:"n",mean:"ケータリング",ex:"Catering will be provided during the reception.",exJa:"レセプション中にケータリングが提供される。",cat:"event"},
  {id:253,word:"raffle",pos:"n",mean:"抽選会",ex:"There will be a raffle after the dinner.",exJa:"夕食後に抽選会が行われる。",cat:"event"},
  {id:254,word:"invitation",pos:"n",mean:"招待状",ex:"Invitations were sent out two weeks ago.",exJa:"招待状は2週間前に送付された。",cat:"event"},
  {id:255,word:"logistics coordinator",pos:"n",mean:"運営担当者",ex:"The logistics coordinator arranged all the details.",exJa:"運営担当者がすべての詳細を手配した。",cat:"event"},
  // ===== 新カテゴリ: 飲食・レストラン =====
  {id:256,word:"reservation",pos:"n",mean:"予約（再掲）",ex:"We made a dinner reservation for eight.",exJa:"8名分の夕食の予約をした。",cat:"dining"},
  {id:257,word:"complimentary",pos:"adj",mean:"サービスの、無料の",ex:"The restaurant offered a complimentary dessert.",exJa:"そのレストランは無料のデザートを提供した。",cat:"dining"},
  {id:258,word:"cuisine",pos:"n",mean:"料理、料理法",ex:"The restaurant specializes in Italian cuisine.",exJa:"そのレストランはイタリア料理を専門としている。",cat:"dining"},
  {id:259,word:"entrée",pos:"n",mean:"主菜",ex:"The entrée comes with a side salad.",exJa:"主菜にはサイドサラダが付いてくる。",cat:"dining"},
  {id:260,word:"tip",pos:"n",mean:"チップ",ex:"A service charge is included, so a tip is optional.",exJa:"サービス料が含まれているのでチップは任意だ。",cat:"dining"},
  {id:261,word:"cater",pos:"v",mean:"料理を提供する",ex:"The company catered the office party.",exJa:"その会社はオフィスパーティーの料理を提供した。",cat:"dining"},
  {id:262,word:"reserve",pos:"v",mean:"予約する",ex:"Please reserve a table in advance.",exJa:"事前にテーブルを予約してください。",cat:"dining"},
  {id:263,word:"menu item",pos:"n",mean:"メニュー品目",ex:"A new menu item was added this season.",exJa:"今シーズン新しいメニュー品目が追加された。",cat:"dining"},
  {id:264,word:"beverage",pos:"n",mean:"飲み物",ex:"Beverages are not included in the price.",exJa:"飲み物は価格に含まれていない。",cat:"dining"},
  {id:265,word:"dietary restriction",pos:"n",mean:"食事制限",ex:"Please inform us of any dietary restrictions.",exJa:"食事制限があればお知らせください。",cat:"dining"},
  // ===== 新カテゴリ: 建設・不動産 =====
  {id:266,word:"lease",pos:"n",mean:"賃貸契約",ex:"The lease expires at the end of the year.",exJa:"賃貸契約は年末に満了する。",cat:"construction"},
  {id:267,word:"tenant",pos:"n",mean:"賃借人、テナント",ex:"The tenant reported a leak in the ceiling.",exJa:"テナントは天井の水漏れを報告した。",cat:"construction"},
  {id:268,word:"contractor",pos:"n",mean:"請負業者",ex:"A local contractor was hired for the renovation.",exJa:"改修工事には地元の請負業者が雇われた。",cat:"construction"},
  {id:269,word:"blueprint",pos:"n",mean:"設計図",ex:"The architect finalized the blueprint.",exJa:"建築家は設計図を最終決定した。",cat:"construction"},
  {id:270,word:"permit",pos:"n",mean:"許可証",ex:"A building permit is required before construction.",exJa:"建設前に建築許可証が必要だ。",cat:"construction"},
  {id:271,word:"renovate",pos:"v",mean:"改修する",ex:"The office will be renovated next month.",exJa:"オフィスは来月改修される予定だ。",cat:"construction"},
  {id:272,word:"premises",pos:"n",mean:"構内、敷地",ex:"Smoking is not allowed on the premises.",exJa:"敷地内での喫煙は禁止されている。",cat:"construction"},
  {id:273,word:"property",pos:"n",mean:"不動産",ex:"They purchased a commercial property downtown.",exJa:"彼らはダウンタウンの商業用不動産を購入した。",cat:"construction"},
  {id:274,word:"zoning",pos:"n",mean:"区画規制",ex:"Local zoning laws restrict building height.",exJa:"地域の区画規制は建物の高さを制限している。",cat:"construction"},
  {id:275,word:"structural",pos:"adj",mean:"構造上の",ex:"The inspection found no structural issues.",exJa:"検査では構造上の問題は見つからなかった。",cat:"construction"},
  // ===== 追加: 形容詞・副詞 =====
  {id:276,word:"prompt",pos:"adj",mean:"迅速な",ex:"We appreciate your prompt response.",exJa:"迅速なご対応に感謝します。",cat:"adj"},
  {id:277,word:"tentative",pos:"adj",mean:"仮の、暫定的な",ex:"This is a tentative schedule and may change.",exJa:"これは暫定的なスケジュールで変更の可能性がある。",cat:"adj"},
  {id:278,word:"consecutive",pos:"adj",mean:"連続した",ex:"She worked five consecutive days.",exJa:"彼女は5日間連続で働いた。",cat:"adj"},
  {id:279,word:"substantial",pos:"adj",mean:"かなりの",ex:"The company made a substantial profit.",exJa:"その会社はかなりの利益を上げた。",cat:"adj"},
  {id:280,word:"apparent",pos:"adj",mean:"明白な",ex:"It became apparent that the plan needed revision.",exJa:"その計画は修正が必要であることが明白になった。",cat:"adj"},
  {id:281,word:"eligible",pos:"adj",mean:"資格のある",ex:"All employees are eligible for the bonus.",exJa:"全従業員がボーナスの対象資格を持つ。",cat:"adj"},
  {id:282,word:"redundant",pos:"adj",mean:"余剰の、冗長な",ex:"Some positions became redundant after the merger.",exJa:"合併後、一部のポジションが余剰になった。",cat:"adj"},
  {id:283,word:"versatile",pos:"adj",mean:"多才な、汎用性のある",ex:"This tool is versatile and easy to use.",exJa:"この道具は汎用性があり使いやすい。",cat:"adj"},
  {id:284,word:"punctual",pos:"adj",mean:"時間厳守の",ex:"Employees are expected to be punctual.",exJa:"従業員は時間厳守が求められる。",cat:"adj"},
  {id:285,word:"concise",pos:"adj",mean:"簡潔な",ex:"Please keep your report concise.",exJa:"報告書は簡潔にしてください。",cat:"adj"},
  {id:286,word:"lucrative",pos:"adj",mean:"儲かる",ex:"They entered a lucrative new market.",exJa:"彼らは儲かる新市場に参入した。",cat:"adj"},
  {id:287,word:"viable",pos:"adj",mean:"実現可能な",ex:"We need a viable solution to this issue.",exJa:"この問題に対する実現可能な解決策が必要だ。",cat:"adj"},
  {id:288,word:"simultaneously",pos:"adv",mean:"同時に",ex:"Both projects were launched simultaneously.",exJa:"両方のプロジェクトが同時に開始された。",cat:"adj"},
  {id:289,word:"consistently",pos:"adv",mean:"一貫して",ex:"Sales have consistently increased this year.",exJa:"今年、売上は一貫して増加している。",cat:"adj"},
  {id:290,word:"promptly",pos:"adv",mean:"迅速に、時間通りに",ex:"The meeting started promptly at nine.",exJa:"会議は9時ちょうどに始まった。",cat:"adj"},
  // ===== 追加: 動詞 =====
  {id:291,word:"undergo",pos:"v",mean:"経験する、受ける",ex:"The building will undergo renovation.",exJa:"その建物は改修を受ける予定だ。",cat:"verb"},
  {id:292,word:"withhold",pos:"v",mean:"差し控える",ex:"The manager withheld approval pending review.",exJa:"マネージャーは審査結果が出るまで承認を差し控えた。",cat:"verb"},
  {id:293,word:"comply",pos:"v",mean:"従う、遵守する",ex:"All staff must comply with safety regulations.",exJa:"全スタッフは安全規則を遵守しなければならない。",cat:"verb"},
  {id:294,word:"facilitate",pos:"v",mean:"促進する、円滑にする",ex:"The new tool facilitates communication.",exJa:"その新しいツールはコミュニケーションを円滑にする。",cat:"verb"},
  {id:295,word:"anticipate",pos:"v",mean:"予期する",ex:"We anticipate strong demand next quarter.",exJa:"来四半期は強い需要を予期している。",cat:"verb"},
  {id:296,word:"withstand",pos:"v",mean:"耐える",ex:"The material can withstand high temperatures.",exJa:"その素材は高温に耐えることができる。",cat:"verb"},
  {id:297,word:"consolidate",pos:"v",mean:"統合する",ex:"The two departments were consolidated into one.",exJa:"2つの部署は1つに統合された。",cat:"verb"},
  {id:298,word:"leverage",pos:"v",mean:"活用する",ex:"The firm leveraged its resources effectively.",exJa:"その会社は資源を効果的に活用した。",cat:"verb"},
  {id:299,word:"exceed",pos:"v",mean:"超える",ex:"Sales exceeded expectations this quarter.",exJa:"今四半期の売上は予想を超えた。",cat:"verb"},
  {id:300,word:"endorse",pos:"v",mean:"承認する、推薦する",ex:"The board endorsed the new policy.",exJa:"取締役会は新方針を承認した。",cat:"verb"},
];
