// TOEIC600点対策 頻出単語データ（カテゴリ別）
const VOCAB_DATA = [
  // ===== ビジネス一般 =====
  {id:1,word:"approve",pos:"v",mean:"承認する",ex:"The manager approved the budget proposal.",exJa:"マネージャーは予算案を承認した。",cat:"business"},
  {id:2,word:"attach",pos:"v",mean:"添付する",ex:"Please attach your resume to the email.",exJa:"履歴書をメールに添付してください。",cat:"business"},
  {id:3,word:"budget",pos:"n",mean:"予算",ex:"We need to stay within budget.",exJa:"予算内に収める必要がある。",cat:"business"},
  {id:4,word:"colleague",pos:"n",mean:"同僚",ex:"She discussed the project with her colleague.",exJa:"彼女は同僚とそのプロジェクトについて話し合った。",cat:"business"},
  {id:5,word:"deadline",pos:"n",mean:"締め切り",ex:"The deadline for the report is Friday.",exJa:"報告書の締め切りは金曜日だ。",cat:"business"},
  {id:6,word:"department",pos:"n",mean:"部署",ex:"He transferred to the sales department.",exJa:"彼は営業部に異動した。",cat:"business"},
  {id:7,word:"employee",pos:"n",mean:"従業員",ex:"All employees must attend the meeting.",exJa:"全従業員が会議に出席しなければならない。",cat:"business"},
  {id:8,word:"invoice",pos:"n",mean:"請求書",ex:"Please send the invoice by email.",exJa:"請求書をメールで送ってください。",cat:"business"},
  {id:9,word:"negotiate",pos:"v",mean:"交渉する",ex:"They negotiated a better contract.",exJa:"彼らはより良い契約を交渉した。",cat:"business"},
  {id:10,word:"postpone",pos:"v",mean:"延期する",ex:"The meeting was postponed until next week.",exJa:"会議は来週まで延期された。",cat:"business"},
  {id:11,word:"promote",pos:"v",mean:"昇進させる",ex:"She was promoted to manager last year.",exJa:"彼女は昨年マネージャーに昇進した。",cat:"business"},
  {id:12,word:"reimburse",pos:"v",mean:"払い戻す",ex:"The company will reimburse travel expenses.",exJa:"会社は旅費を払い戻す。",cat:"business"},
  {id:13,word:"resign",pos:"v",mean:"辞職する",ex:"He decided to resign from his position.",exJa:"彼は職を辞することを決めた。",cat:"business"},
  {id:14,word:"salary",pos:"n",mean:"給料",ex:"Her salary increased after the promotion.",exJa:"昇進後、彼女の給料が上がった。",cat:"business"},
  {id:15,word:"supervisor",pos:"n",mean:"上司、監督者",ex:"Ask your supervisor for approval.",exJa:"承認は上司に求めてください。",cat:"business"},
  {id:16,word:"vacant",pos:"adj",mean:"空いている",ex:"There is a vacant position in marketing.",exJa:"マーケティング部に空きポジションがある。",cat:"business"},
  {id:17,word:"warehouse",pos:"n",mean:"倉庫",ex:"The goods are stored in the warehouse.",exJa:"商品は倉庫に保管されている。",cat:"business"},
  {id:18,word:"merger",pos:"n",mean:"合併",ex:"The merger created a larger company.",exJa:"その合併でより大きな会社が誕生した。",cat:"business"},
  {id:19,word:"revenue",pos:"n",mean:"収益",ex:"Revenue increased by 10% this quarter.",exJa:"今四半期、収益は10%増加した。",cat:"business"},
  {id:20,word:"expense",pos:"n",mean:"経費",ex:"Travel expenses must be reported.",exJa:"旅費は報告しなければならない。",cat:"business"},
  {id:21,word:"shareholder",pos:"n",mean:"株主",ex:"Shareholders attended the annual meeting.",exJa:"株主たちは年次総会に出席した。",cat:"business"},
  {id:22,word:"subsidiary",pos:"n",mean:"子会社",ex:"The subsidiary operates independently.",exJa:"その子会社は独立して運営されている。",cat:"business"},
  {id:23,word:"headquarters",pos:"n",mean:"本社",ex:"The headquarters is located in Tokyo.",exJa:"本社は東京にある。",cat:"business"},
  {id:24,word:"recruit",pos:"v",mean:"採用する",ex:"The company plans to recruit new staff.",exJa:"会社は新しいスタッフを採用する予定だ。",cat:"business"},
  {id:25,word:"qualification",pos:"n",mean:"資格",ex:"She has the qualifications for the job.",exJa:"彼女はその仕事に必要な資格を持っている。",cat:"business"},
  {id:26,word:"candidate",pos:"n",mean:"候補者",ex:"Three candidates applied for the position.",exJa:"3名の候補者がそのポジションに応募した。",cat:"business"},
  {id:27,word:"applicant",pos:"n",mean:"応募者",ex:"The applicant submitted her resume online.",exJa:"応募者はオンラインで履歴書を提出した。",cat:"business"},
  {id:28,word:"performance",pos:"n",mean:"業績、成果",ex:"His performance review is next month.",exJa:"彼の業績評価は来月だ。",cat:"business"},
  {id:29,word:"productivity",pos:"n",mean:"生産性",ex:"New equipment improved productivity.",exJa:"新しい設備が生産性を向上させた。",cat:"business"},
  {id:30,word:"efficient",pos:"adj",mean:"効率的な",ex:"This is a more efficient method.",exJa:"これはより効率的な方法だ。",cat:"business"},
  // ===== オフィス・事務 =====
  {id:31,word:"agenda",pos:"n",mean:"議題",ex:"Please review the agenda before the meeting.",exJa:"会議前に議題を確認してください。",cat:"office"},
  {id:32,word:"draft",pos:"n",mean:"草案",ex:"He wrote the first draft of the report.",exJa:"彼は報告書の初稿を書いた。",cat:"office"},
  {id:33,word:"file",pos:"v",mean:"提出する、ファイルする",ex:"Please file the documents by Friday.",exJa:"金曜日までに書類を提出してください。",cat:"office"},
  {id:34,word:"forward",pos:"v",mean:"転送する",ex:"I will forward your email to the team.",exJa:"あなたのメールをチームに転送します。",cat:"office"},
  {id:35,word:"memo",pos:"n",mean:"メモ、覚書",ex:"She sent a memo to all staff.",exJa:"彼女は全スタッフにメモを送った。",cat:"office"},
  {id:36,word:"notify",pos:"v",mean:"通知する",ex:"We will notify you of any changes.",exJa:"変更があれば通知します。",cat:"office"},
  {id:37,word:"photocopy",pos:"v",mean:"コピーする",ex:"Could you photocopy this document?",exJa:"この書類をコピーしてもらえますか。",cat:"office"},
  {id:38,word:"reception",pos:"n",mean:"受付",ex:"Please check in at the reception desk.",exJa:"受付でチェックインしてください。",cat:"office"},
  {id:39,word:"stationery",pos:"n",mean:"文房具",ex:"We ordered new stationery for the office.",exJa:"オフィス用に新しい文房具を注文した。",cat:"office"},
  {id:40,word:"submit",pos:"v",mean:"提出する",ex:"Submit your application by the deadline.",exJa:"締め切りまでに申込書を提出してください。",cat:"office"},
  {id:41,word:"attendance",pos:"n",mean:"出席",ex:"Attendance at the seminar is mandatory.",exJa:"セミナーへの出席は必須だ。",cat:"office"},
  {id:42,word:"confirm",pos:"v",mean:"確認する",ex:"Please confirm your reservation.",exJa:"予約を確認してください。",cat:"office"},
  {id:43,word:"renew",pos:"v",mean:"更新する",ex:"We need to renew the contract.",exJa:"契約を更新する必要がある。",cat:"office"},
  {id:44,word:"revise",pos:"v",mean:"改訂する",ex:"Please revise the document before sending.",exJa:"送る前に文書を改訂してください。",cat:"office"},
  {id:45,word:"distribute",pos:"v",mean:"配布する",ex:"Handouts were distributed to everyone.",exJa:"配布資料は全員に配られた。",cat:"office"},
  // ===== 会議・コミュニケーション =====
  {id:46,word:"conference",pos:"n",mean:"会議",ex:"The annual conference will be held in March.",exJa:"年次会議は3月に開催される。",cat:"meeting"},
  {id:47,word:"presentation",pos:"n",mean:"発表",ex:"She gave a presentation on the new product.",exJa:"彼女は新製品についての発表をした。",cat:"meeting"},
  {id:48,word:"participant",pos:"n",mean:"参加者",ex:"All participants received a certificate.",exJa:"参加者全員が証明書を受け取った。",cat:"meeting"},
  {id:49,word:"venue",pos:"n",mean:"会場",ex:"The venue for the conference has changed.",exJa:"会議の会場が変更になった。",cat:"meeting"},
  {id:50,word:"reschedule",pos:"v",mean:"予定を変更する",ex:"We had to reschedule the meeting.",exJa:"会議の予定を変更する必要があった。",cat:"meeting"},
  {id:51,word:"discuss",pos:"v",mean:"議論する",ex:"Let's discuss this issue further.",exJa:"この問題についてさらに議論しましょう。",cat:"meeting"},
  {id:52,word:"feedback",pos:"n",mean:"フィードバック",ex:"We appreciate your feedback on the survey.",exJa:"アンケートへのフィードバックに感謝します。",cat:"meeting"},
  {id:53,word:"clarify",pos:"v",mean:"明確にする",ex:"Could you clarify your point?",exJa:"あなたの論点を明確にしてもらえますか。",cat:"meeting"},
  {id:54,word:"brief",pos:"v",mean:"説明する",ex:"He briefed the team on the new policy.",exJa:"彼はチームに新方針について説明した。",cat:"meeting"},
  {id:55,word:"consensus",pos:"n",mean:"合意",ex:"The team reached a consensus.",exJa:"チームは合意に達した。",cat:"meeting"},
  // ===== 出張・旅行 =====
  {id:56,word:"itinerary",pos:"n",mean:"旅程",ex:"Here is the itinerary for your trip.",exJa:"こちらが旅行の旅程です。",cat:"travel"},
  {id:57,word:"departure",pos:"n",mean:"出発",ex:"The departure time was delayed.",exJa:"出発時刻が遅れた。",cat:"travel"},
  {id:58,word:"arrival",pos:"n",mean:"到着",ex:"Please check the arrival gate.",exJa:"到着ゲートを確認してください。",cat:"travel"},
  {id:59,word:"luggage",pos:"n",mean:"荷物",ex:"Please keep your luggage with you.",exJa:"荷物は手元に置いておいてください。",cat:"travel"},
  {id:60,word:"boarding",pos:"n",mean:"搭乗",ex:"Boarding will begin in ten minutes.",exJa:"搭乗は10分後に始まる。",cat:"travel"},
  {id:61,word:"accommodation",pos:"n",mean:"宿泊施設",ex:"We arranged accommodation near the airport.",exJa:"空港近くに宿泊施設を手配した。",cat:"travel"},
  {id:62,word:"reservation",pos:"n",mean:"予約",ex:"I made a reservation for two nights.",exJa:"2泊の予約をした。",cat:"travel"},
  {id:63,word:"fare",pos:"n",mean:"運賃",ex:"The train fare has increased.",exJa:"電車の運賃が上がった。",cat:"travel"},
  {id:64,word:"destination",pos:"n",mean:"目的地",ex:"Our final destination is Osaka.",exJa:"最終目的地は大阪だ。",cat:"travel"},
  {id:65,word:"delay",pos:"n",mean:"遅延",ex:"The flight delay was due to weather.",exJa:"フライトの遅延は天候のためだった。",cat:"travel"},
  // ===== 店舗・小売 =====
  {id:66,word:"merchandise",pos:"n",mean:"商品",ex:"New merchandise arrived this morning.",exJa:"新しい商品が今朝届いた。",cat:"retail"},
  {id:67,word:"discount",pos:"n",mean:"割引",ex:"Customers received a 20% discount.",exJa:"顧客は20%の割引を受けた。",cat:"retail"},
  {id:68,word:"refund",pos:"n",mean:"返金",ex:"You can request a refund within 30 days.",exJa:"30日以内なら返金を申請できる。",cat:"retail"},
  {id:69,word:"warranty",pos:"n",mean:"保証",ex:"The product comes with a one-year warranty.",exJa:"その製品には1年保証が付いている。",cat:"retail"},
  {id:70,word:"inventory",pos:"n",mean:"在庫",ex:"We need to check the inventory.",exJa:"在庫を確認する必要がある。",cat:"retail"},
  {id:71,word:"purchase",pos:"v",mean:"購入する",ex:"She purchased a new laptop.",exJa:"彼女は新しいノートパソコンを購入した。",cat:"retail"},
  {id:72,word:"receipt",pos:"n",mean:"領収書",ex:"Keep your receipt for returns.",exJa:"返品のために領収書を保管してください。",cat:"retail"},
  {id:73,word:"exchange",pos:"v",mean:"交換する",ex:"You can exchange the item for a different size.",exJa:"商品を別のサイズに交換できる。",cat:"retail"},
  {id:74,word:"display",pos:"n",mean:"陳列、展示",ex:"The products are on display in the window.",exJa:"商品はショーウィンドウに展示されている。",cat:"retail"},
  {id:75,word:"retailer",pos:"n",mean:"小売業者",ex:"The retailer offers free shipping.",exJa:"その小売業者は送料無料を提供している。",cat:"retail"},
  // ===== 製造・物流 =====
  {id:76,word:"manufacture",pos:"v",mean:"製造する",ex:"The factory manufactures car parts.",exJa:"その工場は車の部品を製造している。",cat:"manufacturing"},
  {id:77,word:"shipment",pos:"n",mean:"出荷、輸送",ex:"The shipment arrived on time.",exJa:"その出荷は時間通りに到着した。",cat:"manufacturing"},
  {id:78,word:"defect",pos:"n",mean:"欠陥",ex:"The product had a minor defect.",exJa:"その製品には小さな欠陥があった。",cat:"manufacturing"},
  {id:79,word:"durable",pos:"adj",mean:"耐久性のある",ex:"This material is very durable.",exJa:"この素材はとても耐久性がある。",cat:"manufacturing"},
  {id:80,word:"assemble",pos:"v",mean:"組み立てる",ex:"Workers assemble the parts on the line.",exJa:"作業員はラインで部品を組み立てる。",cat:"manufacturing"},
  {id:81,word:"supplier",pos:"n",mean:"供給業者",ex:"We changed our supplier last month.",exJa:"先月、供給業者を変更した。",cat:"manufacturing"},
  {id:82,word:"quality control",pos:"n",mean:"品質管理",ex:"Quality control is essential in manufacturing.",exJa:"品質管理は製造業において不可欠だ。",cat:"manufacturing"},
  {id:83,word:"maintenance",pos:"n",mean:"保守、メンテナンス",ex:"Regular maintenance prevents breakdowns.",exJa:"定期的な保守は故障を防ぐ。",cat:"manufacturing"},
  {id:84,word:"equipment",pos:"n",mean:"設備、機器",ex:"New equipment was installed last week.",exJa:"先週、新しい設備が設置された。",cat:"manufacturing"},
  {id:85,word:"facility",pos:"n",mean:"施設",ex:"The company built a new facility.",exJa:"会社は新しい施設を建設した。",cat:"manufacturing"},
  // ===== 形容詞・副詞（頻出） =====
  {id:86,word:"available",pos:"adj",mean:"利用可能な",ex:"The manager is not available right now.",exJa:"マネージャーは今、対応できません。",cat:"adj"},
  {id:87,word:"reliable",pos:"adj",mean:"信頼できる",ex:"We need a reliable supplier.",exJa:"信頼できる供給業者が必要だ。",cat:"adj"},
  {id:88,word:"essential",pos:"adj",mean:"不可欠な",ex:"Teamwork is essential for success.",exJa:"成功にはチームワークが不可欠だ。",cat:"adj"},
  {id:89,word:"approximately",pos:"adv",mean:"おおよそ",ex:"The trip takes approximately two hours.",exJa:"その旅は約2時間かかる。",cat:"adj"},
  {id:90,word:"frequently",pos:"adv",mean:"頻繁に",ex:"He frequently travels for business.",exJa:"彼は頻繁に出張する。",cat:"adj"},
  {id:91,word:"considerably",pos:"adv",mean:"かなり",ex:"Sales increased considerably this year.",exJa:"今年、売上はかなり増加した。",cat:"adj"},
  {id:92,word:"thoroughly",pos:"adv",mean:"徹底的に",ex:"Please review the contract thoroughly.",exJa:"契約書を徹底的に確認してください。",cat:"adj"},
  {id:93,word:"immediately",pos:"adv",mean:"すぐに",ex:"Please respond immediately.",exJa:"すぐに返信してください。",cat:"adj"},
  {id:94,word:"voluntarily",pos:"adv",mean:"自発的に",ex:"He volunteered to help voluntarily.",exJa:"彼は自発的に手伝うことを申し出た。",cat:"adj"},
  {id:95,word:"significantly",pos:"adv",mean:"著しく",ex:"Costs decreased significantly.",exJa:"コストは著しく減少した。",cat:"adj"},
  {id:96,word:"competent",pos:"adj",mean:"有能な",ex:"She is a competent manager.",exJa:"彼女は有能なマネージャーだ。",cat:"adj"},
  {id:97,word:"flexible",pos:"adj",mean:"柔軟な",ex:"We offer flexible working hours.",exJa:"弊社は柔軟な勤務時間を提供している。",cat:"adj"},
  {id:98,word:"mandatory",pos:"adj",mean:"義務的な",ex:"Attendance is mandatory for all staff.",exJa:"出席は全スタッフにとって義務だ。",cat:"adj"},
  {id:99,word:"comprehensive",pos:"adj",mean:"包括的な",ex:"This is a comprehensive guide.",exJa:"これは包括的なガイドだ。",cat:"adj"},
  {id:100,word:"outstanding",pos:"adj",mean:"未払いの／傑出した",ex:"There is an outstanding balance on your account.",exJa:"あなたの口座には未払い残高がある。",cat:"adj"},
  // ===== 動詞（頻出） =====
  {id:101,word:"accomplish",pos:"v",mean:"成し遂げる",ex:"We accomplished our sales goal.",exJa:"私たちは売上目標を達成した。",cat:"verb"},
  {id:102,word:"acquire",pos:"v",mean:"取得する",ex:"The company acquired a smaller firm.",exJa:"その会社は小さな会社を買収した。",cat:"verb"},
  {id:103,word:"address",pos:"v",mean:"対処する",ex:"We need to address this problem.",exJa:"この問題に対処する必要がある。",cat:"verb"},
  {id:104,word:"allocate",pos:"v",mean:"割り当てる",ex:"Funds were allocated for research.",exJa:"資金は研究のために割り当てられた。",cat:"verb"},
  {id:105,word:"announce",pos:"v",mean:"発表する",ex:"They announced a new product line.",exJa:"彼らは新製品ラインを発表した。",cat:"verb"},
  {id:106,word:"authorize",pos:"v",mean:"許可する",ex:"Only managers can authorize refunds.",exJa:"返金を許可できるのはマネージャーのみだ。",cat:"verb"},
  {id:107,word:"calculate",pos:"v",mean:"計算する",ex:"Please calculate the total cost.",exJa:"総費用を計算してください。",cat:"verb"},
  {id:108,word:"cancel",pos:"v",mean:"中止する",ex:"The flight was cancelled due to weather.",exJa:"フライトは天候のため中止された。",cat:"verb"},
  {id:109,word:"complete",pos:"v",mean:"完了する",ex:"Please complete the form by Monday.",exJa:"月曜日までにフォームを完成させてください。",cat:"verb"},
  {id:110,word:"contribute",pos:"v",mean:"貢献する",ex:"Everyone contributed to the project.",exJa:"全員がそのプロジェクトに貢献した。",cat:"verb"},
  {id:111,word:"determine",pos:"v",mean:"決定する",ex:"We will determine the budget next week.",exJa:"来週、予算を決定する。",cat:"verb"},
  {id:112,word:"establish",pos:"v",mean:"設立する",ex:"The company was established in 1990.",exJa:"その会社は1990年に設立された。",cat:"verb"},
  {id:113,word:"estimate",pos:"v",mean:"見積もる",ex:"We estimate the cost at $5,000.",exJa:"費用は5000ドルと見積もっている。",cat:"verb"},
  {id:114,word:"evaluate",pos:"v",mean:"評価する",ex:"Managers evaluate employee performance.",exJa:"マネージャーは従業員の業績を評価する。",cat:"verb"},
  {id:115,word:"expand",pos:"v",mean:"拡大する",ex:"The company plans to expand overseas.",exJa:"その会社は海外への拡大を計画している。",cat:"verb"},
  {id:116,word:"implement",pos:"v",mean:"実施する",ex:"We will implement the new policy next month.",exJa:"来月、新方針を実施する。",cat:"verb"},
  {id:117,word:"indicate",pos:"v",mean:"示す",ex:"The survey indicates strong customer satisfaction.",exJa:"調査は高い顧客満足度を示している。",cat:"verb"},
  {id:118,word:"launch",pos:"v",mean:"開始する",ex:"The company will launch a new app.",exJa:"その会社は新しいアプリを開始する。",cat:"verb"},
  {id:119,word:"maintain",pos:"v",mean:"維持する",ex:"It is important to maintain good relationships.",exJa:"良い関係を維持することは重要だ。",cat:"verb"},
  {id:120,word:"obtain",pos:"v",mean:"取得する",ex:"You must obtain permission first.",exJa:"まず許可を取得しなければならない。",cat:"verb"},
  {id:121,word:"occur",pos:"v",mean:"起こる",ex:"The error occurred during installation.",exJa:"そのエラーはインストール中に発生した。",cat:"verb"},
  {id:122,word:"prevent",pos:"v",mean:"防ぐ",ex:"This will prevent future problems.",exJa:"これにより将来の問題を防げる。",cat:"verb"},
  {id:123,word:"proceed",pos:"v",mean:"進める",ex:"Let's proceed with the plan.",exJa:"計画を進めましょう。",cat:"verb"},
  {id:124,word:"recommend",pos:"v",mean:"推薦する",ex:"I recommend this restaurant.",exJa:"このレストランをお勧めします。",cat:"verb"},
  {id:125,word:"reduce",pos:"v",mean:"減らす",ex:"We need to reduce costs.",exJa:"コストを削減する必要がある。",cat:"verb"},
  {id:126,word:"replace",pos:"v",mean:"交換する",ex:"The old machine was replaced.",exJa:"古い機械は交換された。",cat:"verb"},
  {id:127,word:"require",pos:"v",mean:"必要とする",ex:"This job requires experience.",exJa:"この仕事には経験が必要だ。",cat:"verb"},
  {id:128,word:"reveal",pos:"v",mean:"明らかにする",ex:"The report revealed new findings.",exJa:"その報告書は新たな発見を明らかにした。",cat:"verb"},
  {id:129,word:"specialize",pos:"v",mean:"専門にする",ex:"She specializes in marketing.",exJa:"彼女はマーケティングを専門にしている。",cat:"verb"},
  {id:130,word:"verify",pos:"v",mean:"確認する",ex:"Please verify your information.",exJa:"あなたの情報を確認してください。",cat:"verb"},
];
